### ISSUE TITLE
Make `cfut.slurm.jobs_finished` more robust

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1249]
We observed a `squeue` commands that failed within a `subprocess.run` call, but we have no immediate visibility into what actually went wrong. The observed traceback in fractal-server logs is e.g.
```python traceback
Traceback (most recent call last):
  File "/somewhere/envs/fractal-server-1.4.0/lib/python3.10/site-packages/fractal_server/app/runner/_slurm/_executor_wait_thread.py", line 124, in check
    finished_jobs = slurm.jobs_finished(self.waiting.values())
  File "/somewhere/envs/fractal-server-1.4.0/lib/python3.10/site-packages/cfut/slurm.py", line 45, in jobs_finished
    res = run([
  File "/somewhere/envs/fractal-server-1.4.0/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['squeue', '--noheader', '--format=%i %T', '--jobs', '10305236', '--states=all']' returned non-zero exit status 1.
```
Note that this is part of `cfut.slurm.jobs_finished` (https://github.com/sampsyo/clusterfutures/blob/e176479d64c2c2aec9f329a53cf177c068adfde4/cfut/slurm.py#L45-L48).

My best guess for the reason is that job 10305236 was not visible in SLURM any more - see below
```
>>> res = subprocess.run(['squeue', '--noheader', '--format=%i %T', '--jobs', '10305236', '--states=all'], check=True)
slurm_load_jobs error: Invalid job id specified
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/xxx/anaconda3/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['squeue', '--noheader', '--format=%i %T', '--jobs', '10305236', '--states=all']' returned non-zero exit status 1.

>>> res = subprocess.run(['squeue', '--noheader', '--format=%i %T', '--jobs', '10305236', '--states=all'], check=False, capture_output=True, encoding="utf-8")
>>> res.stderr
'slurm_load_jobs error: Invalid job id specified\n'
```

### How to fix

Within fractal-server, we could for instance
* Set `check=False` in `subprocess.run`,
* If the subprocess was successful, then proceed
* If the subprocess failed, then:
    * log this information and its stderrr
    * probably mark the job as finished anyway? Or maybe at least we could look for a "slurm_load_jobs error", but I cannot say how robust this would be across SLURM versions.

### SLURM versions
This was tested with
```
$ squeue --version
slurm 15.08.7
```
I cannot say whether this behavior is the same on different versions.

**Comment by tcompa** [comment]
Addendum: I observed the same behavior on SLURM 23.11.2:

```
Python 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> subprocess.run(["squeue", "--jobs 123"], check=True)
squeue: unrecognized option '--jobs 123'
Try "squeue --help" for more information
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['squeue', '--jobs 123']' returned non-zero exit status 1.

```

**Comment by tcompa** [comment]
As a future reference:
* https://slurm.schedmd.com/squeue.html#OPT_SLURM_BITSTR_LEN
* https://bugs.schedmd.com/show_bug.cgi?id=1751
