### ISSUE TITLE
`ValidationError` should raise a 422

### ISSUE THREAD

**Issue by ychiucco** [fractal-analytics-platform/fractal-server#1378]
Traceback reported by @zonia3000 

```
xonya@pjem:~/code/fractal-server (main)*$ poetry run fractalctl set-db
Run alembic.config, with argv=['-c', '/home/xonya/code/fractal-server/fractal_server/alembic.ini', 'upgrade', 'head']
WARNING:root:FRACTAL_TASKS_DIR="Tasks" is not an absolute path; converting it to "/home/xonya/code/fractal-server/Tasks"
2024-04-10 16:13:38,931 - fractal_server.app.db - WARNING - SQLite is supported (for version >=3.37) but discouraged in production. Given its partial support for ForeignKey constraints, database consistency cannot be guaranteed.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 50a13d6138fd, Initial schema
INFO  [alembic.runtime.migration] Running upgrade 50a13d6138fd -> 4c308bcaea2b, Add Task.args_schema and Task.args_schema_version
INFO  [alembic.runtime.migration] Running upgrade 4c308bcaea2b -> f384e1c0cf5d, Drop Task.default_args columns
INFO  [alembic.runtime.migration] Running upgrade f384e1c0cf5d -> 70e77f1c38b0, Add ApplyWorkflow.first_task_index and ApplyWorkflow.last_task_index
INFO  [alembic.runtime.migration] Running upgrade 70e77f1c38b0 -> a7f4d6137b53, Add ApplyWorkflow.workflow_dump
INFO  [alembic.runtime.migration] Running upgrade a7f4d6137b53 -> 8f79bd162e35, Add Task.docs_info and Task.docs_link
INFO  [alembic.runtime.migration] Running upgrade 8f79bd162e35 -> 99ea79d9e5d2, Add Dataset.history
INFO  [alembic.runtime.migration] Running upgrade 99ea79d9e5d2 -> 84bf0fffde30, Add dumps to ApplyWorkflow
INFO  [alembic.runtime.migration] Running upgrade 84bf0fffde30 -> e75cac726012, Make ApplyWorkflow.start_timestamp not nullable
INFO  [alembic.runtime.migration] Running upgrade e75cac726012 -> d4fe3708d309, Make ApplyWorkflow.workflow_dump non-nullable
INFO  [alembic.runtime.migration] Running upgrade d4fe3708d309 -> 71eefd1dd202, add slurm_accounts
INFO  [alembic.runtime.migration] Running upgrade 71eefd1dd202 -> 97f444d47249, add ApplyWorkflow.project_dump
INFO  [alembic.runtime.migration] Running upgrade 97f444d47249 -> efa89c30e0a4, add Project.timestamp_created
INFO  [alembic.runtime.migration] Running upgrade efa89c30e0a4 -> 4cedeb448a53, WorkflowTask foreign keys not nullables
INFO  [alembic.runtime.migration] Running upgrade 4cedeb448a53 -> 9fd26a2b0de4, add Workflow.timestamp_created and Dataset.timestamp_created
INFO  [alembic.runtime.migration] Running upgrade 9fd26a2b0de4 -> d71e732236cd, v2
xonya@pjem:~/code/fractal-server (main)*$ poetry run fractalctl start --port 8000
WARNING:root:FRACTAL_TASKS_DIR="Tasks" is not an absolute path; converting it to "/home/xonya/code/fractal-server/Tasks"
INFO:     Started server process [26112]
INFO:     Waiting for application startup.
2024-04-10 16:13:43,265 - fractal_server.app.db - WARNING - SQLite is supported (for version >=3.37) but discouraged in production. Given its partial support for ForeignKey constraints, database consistency cannot be guaranteed.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:41476 - "GET /auth/current-user/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:41484 - "GET /api/alive/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:41476 - "GET /auth/current-user/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:41496 - "GET /api/v1/task/?args_schema=false HTTP/1.1" 200 OK
INFO:     127.0.0.1:41508 - "POST /api/v1/task/collect/pip/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/xonya/code/fractal-server/fractal_server/app/routes/api/v1/task_collection.py", line 111, in collect_tasks_pip
    venv_path = create_package_dir_pip(task_pkg=task_pkg)
  File "/home/xonya/code/fractal-server/fractal_server/tasks/endpoint_operations.py", line 160, in create_package_dir_pip
    venv_path.mkdir(exist_ok=False, parents=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)

FileExistsError: [Errno 17] File exists: '/home/xonya/code/fractal-server/Tasks/.fractal/fractal-tasks-core0.14.3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xonya/.cache/pypoetry/virtualenvs/fractal-server-b9daiYIL-py3.10/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 412, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/xonya/.cache/pypoetry/virtualenvs/fractal-server-b9daiYIL-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/xonya/.cache/pypoetry/virtualenvs/fractal-server-b9daiYIL-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/xonya/.cache/pypoetry/virtualenvs/fractal-server-b9daiYIL-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/xonya/.cache/pypoetry/virtualenvs/fractal-server-b9daiYIL-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/xonya/.cache/pypoetry/virtualenvs/fractal-server-b9daiYIL-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/xonya/.cache/pypoetry/virtualenvs/fractal-server-b9daiYIL-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/xonya/.cache/pypoetry/virtualenvs/fractal-server-b9daiYIL-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/xonya/.cache/pypoetry/virtualenvs/fractal-server-b9daiYIL-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/xonya/.cache/pypoetry/virtualenvs/fractal-server-b9daiYIL-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/xonya/.cache/pypoetry/virtualenvs/fractal-server-b9daiYIL-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/home/xonya/.cache/pypoetry/virtualenvs/fractal-server-b9daiYIL-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/home/xonya/.cache/pypoetry/virtualenvs/fractal-server-b9daiYIL-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/xonya/.cache/pypoetry/virtualenvs/fractal-server-b9daiYIL-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/xonya/.cache/pypoetry/virtualenvs/fractal-server-b9daiYIL-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/xonya/.cache/pypoetry/virtualenvs/fractal-server-b9daiYIL-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
  File "/home/xonya/.cache/pypoetry/virtualenvs/fractal-server-b9daiYIL-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/home/xonya/.cache/pypoetry/virtualenvs/fractal-server-b9daiYIL-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/home/xonya/.cache/pypoetry/virtualenvs/fractal-server-b9daiYIL-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)

  File "/home/xonya/code/fractal-server/fractal_server/app/routes/api/v1/task_collection.py", line 115, in collect_tasks_pip
    task_collect_status = get_collection_data(venv_path)
  File "/home/xonya/code/fractal-server/fractal_server/tasks/v1/get_collection_data.py", line 14, in get_collection_data
    return TaskCollectStatusV1(**data)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 12 validation errors for TaskCollectStatusV1
task_list -> 0 -> is_v2_compatible
  field required (type=value_error.missing)
task_list -> 1 -> is_v2_compatible
  field required (type=value_error.missing)
task_list -> 2 -> is_v2_compatible
  field required (type=value_error.missing)
task_list -> 3 -> is_v2_compatible
  field required (type=value_error.missing)
task_list -> 4 -> is_v2_compatible
  field required (type=value_error.missing)
task_list -> 5 -> is_v2_compatible
  field required (type=value_error.missing)
task_list -> 6 -> is_v2_compatible
  field required (type=value_error.missing)
task_list -> 7 -> is_v2_compatible
  field required (type=value_error.missing)
task_list -> 8 -> is_v2_compatible
  field required (type=value_error.missing)
task_list -> 9 -> is_v2_compatible
  field required (type=value_error.missing)
task_list -> 10 -> is_v2_compatible
  field required (type=value_error.missing)
task_list -> 11 -> is_v2_compatible
  field required (type=value_error.missing)
```

**Comment by tcompa** [comment]
How to reproduce within a test:
1. Create the appropriate folder, and create a `collection.json` file with some arbitrary content.
2. Trigger task collection

**Comment by tcompa** [comment]
Ref https://github.com/fractal-analytics-platform/fractal-server/blob/2119ad731b6826bba2f9382ad69c70db52004ad4/fractal_server/app/routes/api/v2/task_collection.py#L133, where we should add another `except` option

(I suggest we fix this in both V1 and V2 endpoints)
