### ISSUE TITLE
Fix `assemble_history_failed_job` in case of Unknown Error

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1390]
See second part of 
```python traceback
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/somewhere/fractal-server/fractal_server/app/runner/v2/__init__.py", line 202, in submit_workflow
    new_dataset_attributes = await process_workflow(
  File "/somewhere/fractal-server/fractal_server/app/runner/v2/_local/__init__.py", line 154, in process_workflow
    new_dataset_attributes = await async_wrap(_process_workflow)(
  File "/somewhere/fractal-server/fractal_server/app/runner/async_wrap.py", line 25, in async_wrapper
    return await loop.run_in_executor(executor, pfunc)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/somewhere/fractal-server/fractal_server/app/runner/v2/_local/__init__.py", line 54, in _process_workflow
    new_dataset_attributes = execute_tasks_v2(
  File "/somewhere/fractal-server/fractal_server/app/runner/v2/runner.py", line 114, in execute_tasks_v2
    current_task_output = run_v1_task_parallel(
TypeError: run_v1_task_parallel() missing 1 required keyword-only argument: 'workflow_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/somewhere/else//lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/somewhere/else//lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/somewhere/else//lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/somewhere/else//lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/somewhere/else//lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/somewhere/else//lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/somewhere/else//lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/somewhere/else//lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/somewhere/else//lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/somewhere/else//lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/somewhere/else//lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/somewhere/else//lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/somewhere/else//lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/somewhere/else//lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/somewhere/else//lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/somewhere/else//lib/python3.10/site-packages/starlette/routing.py", line 75, in app
    await response(scope, receive, send)
  File "/somewhere/else//lib/python3.10/site-packages/starlette/responses.py", line 162, in __call__
    await self.background()
  File "/somewhere/else//lib/python3.10/site-packages/starlette/background.py", line 45, in __call__
    await task()
  File "/somewhere/else//lib/python3.10/site-packages/starlette/background.py", line 28, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/somewhere/fractal-server/fractal_server/app/runner/v2/__init__.py", line 312, in submit_workflow
    dataset.history = assemble_history_failed_job(
  File "/somewhere/fractal-server/fractal_server/app/runner/v2/handle_failed_job.py", line 100, in assemble_history_failed_job
    failed_wftask_dump["task"] = failed_wftask.task.model_dump()
AttributeError: 'NoneType' object has no attribute 'model_dump'
```

**Comment by tcompa** [comment]
For the record, this traceback
```python traceback
    failed_wftask_dump["task"] = failed_wftask.task.model_dump()
AttributeError: 'NoneType' object has no attribute 'model_dump'
```
is likely related to the difference between V1 and V2 tasks (both to be supported in the V2 runner).

---

Anyway, we must re-enable the unknown-error full-workflow test.
