### ISSUE TITLE
To review: A task argument is set to empty string for no obvious reason

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1409]
This is likely not a task error, but I'll take a note here.

I ran an example in fractal-web, and then re-ran it with `overwrite=True` for all tasks.

The error traceback read
```python traceback
TASK ERROR: Task name: Convert Cellvoyager to OME-Zarr, position in Workflow: 0
TRACEBACK:
2024-04-17 12:19:37,405; INFO; START cellvoyager_to_ome_zarr_init task
2024-04-17 12:19:37,405; INFO; [glob_with_multiple_patterns] patterns=['*.png']
2024-04-17 12:19:37,405; INFO; [glob_with_multiple_patterns] Found 4 items
2024-04-17 12:19:37,406; INFO; Creating 20200812-CardiomyocyteDifferentiation14-Cycle1.zarr
2024-04-17 12:19:37,406; INFO; Start open_zarr_group_with_overwrite (overwrite=True).
2024-04-17 12:19:37,419; INFO; Zarr group /tmp/newnew/20200812-CardiomyocyteDifferentiation14-Cycle1.zarr already exists, with keys=['B']
2024-04-17 12:19:37,425; WARNING; Since a custom metadata table was provided, there will be no additional check on the number of image files.
Traceback (most recent call last):
  File "/home/tommaso/Fractal/fractal-server/tests/data/example_server_startup/Tasks/.fractal/fractal-tasks-core1.0.0a1/venv/lib/python3.10/site-packages/fractal_tasks_core/tasks/cellvoyager_to_ome_zarr_init.py", line 469, in <module>
    run_fractal_task(
  File "/home/tommaso/Fractal/fractal-server/tests/data/example_server_startup/Tasks/.fractal/fractal-tasks-core1.0.0a1/venv/lib/python3.10/site-packages/fractal_tasks_core/tasks/_utils.py", line 79, in run_fractal_task
    metadata_update = task_function(**pars)
  File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
  File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
  File "pydantic/decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
  File "/home/tommaso/Fractal/fractal-server/tests/data/example_server_startup/Tasks/.fractal/fractal-tasks-core1.0.0a1/venv/lib/python3.10/site-packages/fractal_tasks_core/tasks/cellvoyager_to_ome_zarr_init.py", line 260, in cellvoyager_to_ome_zarr_init
    site_metadata = pd.read_csv(metadata_table_file)
  File "/home/tommaso/Fractal/fractal-server/tests/data/example_server_startup/Tasks/.fractal/fractal-tasks-core1.0.0a1/venv/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/tommaso/Fractal/fractal-server/tests/data/example_server_startup/Tasks/.fractal/fractal-tasks-core1.0.0a1/venv/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/tommaso/Fractal/fractal-server/tests/data/example_server_startup/Tasks/.fractal/fractal-tasks-core1.0.0a1/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/tommaso/Fractal/fractal-server/tests/data/example_server_startup/Tasks/.fractal/fractal-tasks-core1.0.0a1/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/tommaso/Fractal/fractal-server/tests/data/example_server_startup/Tasks/.fractal/fractal-tasks-core1.0.0a1/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/tommaso/Fractal/fractal-server/tests/data/example_server_startup/Tasks/.fractal/fractal-tasks-core1.0.0a1/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/home/tommaso/Fractal/fractal-server/tests/data/example_server_startup/Tasks/.fractal/fractal-tasks-core1.0.0a1/venv/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: ''
```

while the args file is
```json
{
  "zarr_urls": [
    "/tmp/newnew/20200812-CardiomyocyteDifferentiation14-Cycle1_mip.zarr/B/03/0"
  ],
  "zarr_dir": "/tmp/newnew",
  "num_levels": 5,
  "coarsening_xy": 2,
  "image_extension": "png",
  "overwrite": true,
  "image_dirs": [
    "/home/tommaso/Fractal/fractal-demos/examples/01_cardio_tiny_dataset/../images/10.5281_zenodo.8287221/"
  ],
  "allowed_channels": [
    {
      "color": "00FFFF",
      "wavelength_id": "A01_C01",
      "label": "DAPI",
      "window": {
        "start": 110,
        "end": 800,
        "min": null,
        "max": null
      },
      "index": null,
      "active": true,
      "coefficient": 1,
      "inverted": false
    },
    {
      "color": "FF00FF",
      "wavelength_id": "A01_C02",
      "label": "nanog",
      "window": {
        "start": 110,
        "end": 290,
        "min": null,
        "max": null
      },
      "index": null,
      "active": true,
      "coefficient": 1,
      "inverted": false
    },
    {
      "color": "FFFF00",
      "wavelength_id": "A02_C03",
      "label": "Lamin B1",
      "window": {
        "start": 110,
        "end": 1600,
        "min": null,
        "max": null
      },
      "index": null,
      "active": true,
      "coefficient": 1,
      "inverted": false
    }
  ],
  "image_glob_patterns": [],
  "metadata_table_file": ""
}
```

What is clearly wrong is `"metadata_table_file": ""`, but I cannot say where this comes from.

**Comment by tcompa** [comment]
Note: this was with [df4f512](https://github.com/fractal-analytics-platform/fractal-server/pull/1408/commits/df4f512758b0174597c4b4602b87205c88514d20), and it probably has to do with the latest changes related to #1405.

**Comment by jluethi** [comment]
One part that is very suspicious:
`2024-04-17 12:19:37,425; WARNING; Since a custom metadata table was provided, there will be no additional check on the number of image files.`

Do we handle unset arguments/Nones different somehow? I wouldn't expect this code path to be used based on the settings

**Comment by tcompa** [comment]
> One part that is very suspicious: `2024-04-17 12:19:37,425; WARNING; Since a custom metadata table was provided, there will be no additional check on the number of image files.`

Agreed, see :

> What is clearly wrong is "metadata_table_file": "", but I cannot say where this comes from.

---

> Do we handle unset arguments/Nones different somehow? I wouldn't expect this code path to be used based on the settings

My guess is that the reason is https://github.com/fractal-analytics-platform/fractal-web/issues/455, TBD.

**Comment by tcompa** [comment]
Fixed in fractal-web - ref https://github.com/fractal-analytics-platform/fractal-web/pull/457
