### ISSUE TITLE
Fix internal error related to unset job folder

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1447]
This took place with fractal-server 1.4.10. TBD whether it's still relevant

```
[2024-04-11 10:21:15 +0000] [7255] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/somewhere/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 412, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/somewhere/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/somewhere/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/somewhere/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/somewhere/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/somewhere/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/somewhere/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/somewhere/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/somewhere/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/somewhere/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/somewhere/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/somewhere/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/somewhere/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/somewhere/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/somewhere/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/somewhere/lib/python3.10/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
  File "/somewhere/lib/python3.10/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/somewhere/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/somewhere/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/somewhere/lib/python3.10/site-packages/fractal_server/app/routes/admin.py", line 365, in stop_job
    _write_shutdown_file(job=job)
  File "/somewhere/lib/python3.10/site-packages/fractal_server/app/routes/aux/_job.py", line 21, in _write_shutdown_file
    shutdown_file = Path(job.working_dir) / SHUTDOWN_FILENAME
  File "/somewhere/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/somewhere/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/somewhere/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by tcompa** [comment]
The same error (`job.working_dir=None`) also appeared as part of https://github.com/fractal-analytics-platform/fractal-server/issues/1463#issue-2278039053.

Proposed solution: let's move the folder definition to the job-creation endpoint, rather than doing it donwstream as part of the runnner background job. This way we can make it a required column of the `jobv2` table, and avoid this issue.

**Comment by tcompa** [comment]
> This way we can make it a required column of the jobv2 table, and avoid this issue.

Addendum: we cannot actually make the column required, since the folder path needs the job ID, which is only known after it's created. But we can still bring the two operations as close as possible, to mitigate this issue.

**Comment by tcompa** [comment]
As of #1464 (to be included in upcoming version 2.0.5), this error should be much less likely - or at least it should take place right away within the endpoint in a more visible way.

Let's re-open if we hit it again.

**Comment by tcompa** [comment]
Still happening in 2.0.5:
```
[2024-05-13 10:03:15 +0000] [22366] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/somewhere/anaconda3/envs/fractal-server-2.0.5/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/somewhere/anaconda3/envs/fractal-server-2.0.5/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/somewhere/anaconda3/envs/fractal-server-2.0.5/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/somewhere/anaconda3/envs/fractal-server-2.0.5/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/somewhere/anaconda3/envs/fractal-server-2.0.5/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/somewhere/anaconda3/envs/fractal-server-2.0.5/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/somewhere/anaconda3/envs/fractal-server-2.0.5/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/somewhere/anaconda3/envs/fractal-server-2.0.5/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/somewhere/anaconda3/envs/fractal-server-2.0.5/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/somewhere/anaconda3/envs/fractal-server-2.0.5/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/somewhere/anaconda3/envs/fractal-server-2.0.5/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/somewhere/anaconda3/envs/fractal-server-2.0.5/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/somewhere/anaconda3/envs/fractal-server-2.0.5/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/somewhere/anaconda3/envs/fractal-server-2.0.5/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/somewhere/anaconda3/envs/fractal-server-2.0.5/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/somewhere/anaconda3/envs/fractal-server-2.0.5/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/somewhere/anaconda3/envs/fractal-server-2.0.5/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/somewhere/anaconda3/envs/fractal-server-2.0.5/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/somewhere/anaconda3/envs/fractal-server-2.0.5/lib/python3.10/site-packages/fractal_server/app/routes/admin/v1.py", line 365, in stop_job
    _write_shutdown_file(job=job)
  File "/somewhere/anaconda3/envs/fractal-server-2.0.5/lib/python3.10/site-packages/fractal_server/app/routes/aux/_job.py", line 21, in _write_shutdown_file
    shutdown_file = Path(job.working_dir) / SHUTDOWN_FILENAME
  File "/somewhere/anaconda3/envs/fractal-server-2.0.5/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/somewhere/anaconda3/envs/fractal-server-2.0.5/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/somewhere/anaconda3/envs/fractal-server-2.0.5/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by tcompa** [comment]
> Still happening in 2.0.5:

I take it back.
All recent jobs (created with v2.0.5) have the working dir set. This was probably one of the "bugged" jobs, without working dir, and while running 2.0.5 I was trying to stop it.
