### ISSUE TITLE
`linkuserprojectv2` loosing an entry??

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#1463]
Matteo & @barbsilv hit a very weird issue this evening: Matteo was running 2 jobs in a project in Fractal V2. When he went back 2 hours later, the project appears to have disappeared.

What has actually happened?
The `linkuserprojectv2` appears to have lost the entry linking Matteo's user to the project. Therefore, it disappeared for him in the web interface.

The 2 workflows that were running in that project both failed around 17:18 / 17:19 today with a task error (input parameter validation failed for the third task in the workflow):
<img width="1434" alt="Screenshot 2024-05-03 at 18 00 29" src="https://github.com/fractal-analytics-platform/fractal-server/assets/18033446/56701880-a901-495e-9a1a-a190ec08298a">

About a minute before, there was an uncaught exception on the Fractal server backend side (from the server log):
```
[2024-05-03 17:17:42 +0200] [909132] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/path/to/server-envs/fractal-server-2.0.1/lib64/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/path/to/server-envs/fractal-server-2.0.1/lib64/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/path/to/server-envs/fractal-server-2.0.1/lib64/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/path/to/server-envs/fractal-server-2.0.1/lib64/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/path/to/server-envs/fractal-server-2.0.1/lib64/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/path/to/server-envs/fractal-server-2.0.1/lib64/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/path/to/server-envs/fractal-server-2.0.1/lib64/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/path/to/server-envs/fractal-server-2.0.1/lib64/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/path/to/server-envs/fractal-server-2.0.1/lib64/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/path/to/server-envs/fractal-server-2.0.1/lib64/python3.9/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/path/to/server-envs/fractal-server-2.0.1/lib64/python3.9/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/path/to/server-envs/fractal-server-2.0.1/lib64/python3.9/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/path/to/server-envs/fractal-server-2.0.1/lib64/python3.9/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/path/to/server-envs/fractal-server-2.0.1/lib64/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/path/to/server-envs/fractal-server-2.0.1/lib64/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/path/to/server-envs/fractal-server-2.0.1/lib64/python3.9/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/path/to/server-envs/fractal-server-2.0.1/lib64/python3.9/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/path/to/server-envs/fractal-server-2.0.1/lib64/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/path/to/server-envs/fractal-server-2.0.1/lib64/python3.9/site-packages/fractal_server/app/routes/api/v2/status.py", line 121, in get_workflowtask_status
    tmp_file = Path(running_job.working_dir) / HISTORY_FILENAME
  File "/usr/lib64/python3.9/pathlib.py", line 1082, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib64/python3.9/pathlib.py", line 707, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib64/python3.9/pathlib.py", line 691, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I investigated this around 6pm when the error was detected. 

I then dug into the database and saw the following: The project (id 11, name 0026_homeo_lipidmito) still exists in the database. That's why the failed jobs show up in the fractal admin panel. In the admin panel, it still lists matteo's email as the owner. But when I filter for jobs by Matteo, those don't show up anymore.

<img width="1466" alt="Screenshot 2024-05-03 at 18 27 21" src="https://github.com/fractal-analytics-platform/fractal-server/assets/18033446/992d11ff-4529-4af0-a959-5d1f79ae49ff">

Project 11 is still in the db, still has workflows etc. But the `linkuserprojectv2` has no entries for that project anymore.

I currently have no idea what could have caused this. For further context:
Multiple users were running projects at that time. Matteo last saw his project around an hour or so before 17:18 when the jobs failed, when he returned to Fractal web around 17:45, the project wasn't visible for him anymore. He had 2 similar workflow running that both failed and some other workflows also failed. Also, the 1536 well jobs were running at the same time (see https://github.com/fractal-analytics-platform/fractal-server/issues/1459), though that should be unrelated.

**Comment by jluethi** [comment]
This issue seems to happen again on the fractal-server 2.0.1 server we have running at FMI. It apparently affects both V1 & V2 projects.

Just dumping some more observations in here:
I got a report of issues this morning at 9:14. The server .err logs show the following
```
[2024-05-12 14:01:53 +0200] [1820093] [INFO] Application startup complete.
[2024-05-12 16:02:46 +0200] [646227] [CRITICAL] WORKER TIMEOUT (pid:909131)
[2024-05-12 16:02:47 +0200] [646227] [ERROR] Worker (pid:909131) was sent SIGKILL! Perhaps out of memory?
[2024-05-12 16:03:07 +0200] [1821791] [INFO] Booting worker with pid: 1821791
[2024-05-12 16:03:09 +0200] [1821791] [INFO] Started server process [1821791]
[2024-05-12 16:03:09 +0200] [1821791] [INFO] Waiting for application startup.
[2024-05-12 16:03:09 +0200] [1821791] [INFO] Application startup complete.
[2024-05-13 09:01:34 +0200] [646227] [CRITICAL] WORKER TIMEOUT (pid:1820079)
[2024-05-13 09:01:34 +0200] [646227] [CRITICAL] WORKER TIMEOUT (pid:1820080)
[2024-05-13 09:01:34 +0200] [646227] [CRITICAL] WORKER TIMEOUT (pid:1820082)
[2024-05-13 09:01:34 +0200] [646227] [CRITICAL] WORKER TIMEOUT (pid:1820093)
[2024-05-13 09:01:34 +0200] [646227] [CRITICAL] WORKER TIMEOUT (pid:1821791)
[2024-05-13 09:01:35 +0200] [646227] [ERROR] Worker (pid:1820093) was sent code 134!
[2024-05-13 09:01:35 +0200] [646227] [ERROR] Worker (pid:1820082) was sent code 134!
[2024-05-13 09:01:35 +0200] [646227] [ERROR] Worker (pid:1821791) was sent code 134!
[2024-05-13 09:01:35 +0200] [646227] [ERROR] Worker (pid:1820080) was sent code 134!
[2024-05-13 09:01:35 +0200] [646227] [ERROR] Worker (pid:1820079) was sent code 134!
```

I don't know whether these errors are related, but the timing is suspicious.

I also got user reports of similar issues though on 9/5 and there is nothing in the fractal server .err log for that day at all.

The error from above doesn't show up on either day.

---------

In an unrelated note, one thing that seemed suspicious to me:
The workflow is run as:
```
2024-05-13 08:43:31,289 - WF4_job124 - INFO - End execution of workflow "Workflow 2D to 3D ExM - fractal 0.14.2 - fractalWeb 2.0 - 240220-SB-000-AAB-SF-D04"; more logs at /tungstenfs/landing/fractal/20230626_deployment_130/fractal_logs/proj_0000005_wf_0000004_job_0000124_20240513_064255/workflow.log
```
This makes it look as if the project id was 5 (because `proj_0000005` is in the log path). But in reality, the project id was 224.
Adding back project 224 to the linking table fixed the issue. Is this expected behavior that project 224 would have its logs in the `proj_0000005` folder?? => cc @tcompa

**Comment by jluethi** [comment]
Other relevant observation: The user is switching back & forth between V1 & V2, running workflows on both (sometimes at the same time). I haven't seen anything that points to this as an issue, but adding this for completeness.

**Comment by tcompa** [comment]
> Is this expected behavior that project 224 would have its logs in the proj_0000005 folder?? => cc @tcompa

Not at all.

> Adding back project 224 to the linking table fixed the issue.

Could you add a couple more details?
1. How did you add it back (was it directly via `psql`?)
2. Could you spot any "spurious" entry in the `linkuserproject` table before the fix (e.g. one related to project 5 rather than 224)?

Thanks

**Comment by tcompa** [comment]
Another question: which projects with ID equal to 5 or 224 and with version v1 or v2 do exist? Do they belong to the same user?

**Comment by jluethi** [comment]
> How did you add it back (was it directly via psql?)

Yes, manually via psql: INSERT INTO linkuserproject (project_id, user_id) VALUES (224, 17);

> Could you spot any "spurious" entry in the linkuserproject table before the fix (e.g. one related to project 5 rather than 224)?

All in V1:
Before I added the project 224, project 5 was already in the linking table associated to my user (while 224 was supposed to be linked to a different user). That was all in the V1 tables. And that did not change after I added the 224 entry.
Project 5 really still exists and my user still has access to it. 

The V2 tables:
A project 5 exists and belongs to the user that should own project 224. No project 224 exists.

**Comment by jluethi** [comment]
Ok, turns out the IDs were all fine, this was actually a V2 job that was running.
The confusion came up because the user named their V2 workflow: "Workflow 2D to 3D ExM - fractal 0.14.2" (and 0.14.2 tasks only work in V1). But it actually contained 1.0.2 tasks, so all fine

**Comment by tcompa** [comment]
Possibly related: https://github.com/fractal-analytics-platform/fractal-web/issues/499#issuecomment-2136774263

**Comment by tcompa** [comment]
We did spot another instance of of this issue on the pelkmanslab Fractal instance, in the early days of fractal v2.

ProjectV2 13 exists, but is not linked to any user.

Note that the project was created, then workflow 12 was associated to it (meaning that the project was still associated to a user), then worfklowtask 31 was associated to it (meaning that the project was still associated to a user), based on taskv2 32.
Something went wrong _after_ this set of activities, but before any dataset was created within this project.


```
fractal=# select * from projectv2;
 id |                  name                  |       timestamp_created       
----+----------------------------------------+-------------------------------
 13 | TEST_PROJECT_V2                        | 2024-05-02 12:19:50.684099+00
[...]
(25 rows)

fractal=# select * from linkuserprojectv2 order by project_id;
 project_id | user_id 
------------+---------
          4 |       6
         16 |      37
[...]
(24 rows)
```

---

With @mfranzon, we still cannot come up with any good explanation - nor we understand why it seems that this was inadvertently fixed with some later version.

I will now associate the project to my own user (with `INSERT INTO linkuserprojectv2 (project_id, user_id) VALUES (13, XXXX);`) and then remove unless it includes anything relevant.
