### ISSUE TITLE
Workflow submissions fail in fractal-server 2.0.3

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#1478]
Last successful workflow submission was on 8/5 according to the logs. Since 10/5, we are getting the following errors upon workflow submission:

```
[2024-05-13 07:30:03 +0000] [28509] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
    await response(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/responses.py", line 162, in __call__
    await self.background()
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/background.py", line 45, in __call__
    await task()
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/background.py", line 28, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/fractal_server/app/runner/v2/__init__.py", line 119, in submit_workflow
    ).resolve()
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/pathlib.py", line 1077, in resolve
    s = self._accessor.realpath(self, strict=strict)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/posixpath.py", line 397, in realpath
    return abspath(path)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/posixpath.py", line 384, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
```

Or:
```
Traceback (most recent call last):
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/site-packages/fractal_server/app/routes/api/v2/status.py", line 139, in get_workflowtask_status
    tmp_file = Path(running_job.working_dir) / HISTORY_FILENAME
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-2.0.3/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

In both cases, the workflow is marked as running, but never actually appears to start. And it also never finished (and can't be cancelled), as it never reaches the slurm cluster.

**Comment by tcompa** [comment]
For the record, logs suggest there are two issues:

1. An issue within the get-status endpoint, which was already reported elsewhere. This is a consequence of the job DB entry having a `null` working directory (ref #1446), as I just verified by manually looking into the DB. Version 2.0.5 is meant to mitigate this issue.
2. A new issue with the job-execution function (the first error traceback, in your report), which we haven't observed yet. The failure of `os.getcwd()` would be explained e.g. with a folder that was removed, but it's not clear yet how we could hit this situation.

**Comment by tcompa** [comment]
Issue 2 was related to a (currently unclear) system issue, affecting both fractal-server and fractal-web.
Issue 1 is similar to #1446, and it should be at least mitigated by v2.0.5. Let's re-open #1446 if we hit it again.
