### ISSUE TITLE
Fix GHA issue by clearing cache

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1571]
Related issue: https://github.com/pypa/virtualenv/issues/2735

Failed workflow: https://github.com/fractal-analytics-platform/fractal-server/actions/runs/9583566590/job/26425273607

Logs
```
2024-06-19T14:15:36.5837604Z Current runner version: '2.317.0'
2024-06-19T14:15:36.5868309Z ##[group]Operating System
2024-06-19T14:15:36.5869390Z Ubuntu
2024-06-19T14:15:36.5869919Z 22.04.4
2024-06-19T14:15:36.5870503Z LTS
2024-06-19T14:15:36.5871260Z ##[endgroup]
2024-06-19T14:15:36.5871881Z ##[group]Runner Image
2024-06-19T14:15:36.5872653Z Image: ubuntu-22.04
2024-06-19T14:15:36.5873531Z Version: 20240616.1.0
2024-06-19T14:15:36.5875137Z Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240616.1/images/ubuntu/Ubuntu2204-Readme.md
2024-06-19T14:15:36.5877521Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240616.1
2024-06-19T14:15:36.5879094Z ##[endgroup]
2024-06-19T14:15:36.5879726Z ##[group]Runner Image Provisioner
2024-06-19T14:15:36.5880497Z 2.0.370.1
2024-06-19T14:15:36.5881199Z ##[endgroup]
2024-06-19T14:15:36.5884948Z ##[group]GITHUB_TOKEN Permissions
2024-06-19T14:15:36.5887499Z Actions: write
2024-06-19T14:15:36.5888414Z Attestations: write
2024-06-19T14:15:36.5889427Z Checks: write
2024-06-19T14:15:36.5890026Z Contents: write
2024-06-19T14:15:36.5890853Z Deployments: write
2024-06-19T14:15:36.5891621Z Discussions: write
2024-06-19T14:15:36.5892243Z Issues: write
2024-06-19T14:15:36.5892839Z Metadata: read
2024-06-19T14:15:36.5893244Z Packages: write
2024-06-19T14:15:36.5893596Z Pages: write
2024-06-19T14:15:36.5894058Z PullRequests: write
2024-06-19T14:15:36.5894478Z RepositoryProjects: write
2024-06-19T14:15:36.5894885Z SecurityEvents: write
2024-06-19T14:15:36.5895365Z Statuses: write
2024-06-19T14:15:36.5895765Z ##[endgroup]
2024-06-19T14:15:36.5899015Z Secret source: Actions
2024-06-19T14:15:36.5899733Z Prepare workflow directory
2024-06-19T14:15:36.6519691Z Prepare all required actions
2024-06-19T14:15:36.6675556Z Getting action download info
2024-06-19T14:15:36.8311128Z Download action repository 'actions/checkout@v4' (SHA:692973e3d937129bcbf40652eb9f2f61becf3332)
2024-06-19T14:15:37.2788705Z Download action repository 'actions/setup-python@v5' (SHA:82c7e631bb3cdc910f68e0081d67478d79c6982d)
2024-06-19T14:15:37.4764767Z Complete job name: build
2024-06-19T14:15:37.5729017Z ##[group]Run actions/checkout@v4
2024-06-19T14:15:37.5729559Z with:
2024-06-19T14:15:37.5730057Z   repository: fractal-analytics-platform/fractal-server
2024-06-19T14:15:37.5731005Z   token: ***
2024-06-19T14:15:37.5731392Z   ssh-strict: true
2024-06-19T14:15:37.5731738Z   ssh-user: git
2024-06-19T14:15:37.5732226Z   persist-credentials: true
2024-06-19T14:15:37.5732671Z   clean: true
2024-06-19T14:15:37.5733030Z   sparse-checkout-cone-mode: true
2024-06-19T14:15:37.5733617Z   fetch-depth: 1
2024-06-19T14:15:37.5734007Z   fetch-tags: false
2024-06-19T14:15:37.5734364Z   show-progress: true
2024-06-19T14:15:37.5735353Z   lfs: false
2024-06-19T14:15:37.5735693Z   submodules: false
2024-06-19T14:15:37.5736111Z   set-safe-directory: true
2024-06-19T14:15:37.5736910Z ##[endgroup]
2024-06-19T14:15:37.7683752Z Syncing repository: fractal-analytics-platform/fractal-server
2024-06-19T14:15:37.7687075Z ##[group]Getting Git version info
2024-06-19T14:15:37.7689006Z Working directory is '/home/runner/work/fractal-server/fractal-server'
2024-06-19T14:15:37.7690911Z [command]/usr/bin/git version
2024-06-19T14:15:37.7691709Z git version 2.45.2
2024-06-19T14:15:37.7720797Z ##[endgroup]
2024-06-19T14:15:37.7740160Z Temporarily overriding HOME='/home/runner/work/_temp/f1fd29ba-00c6-45b8-a944-4a8393847248' before making global git config changes
2024-06-19T14:15:37.7741819Z Adding repository directory to the temporary git global config as a safe directory
2024-06-19T14:15:37.7747236Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/fractal-server/fractal-server
2024-06-19T14:15:37.7789374Z Deleting the contents of '/home/runner/work/fractal-server/fractal-server'
2024-06-19T14:15:37.7794063Z ##[group]Initializing the repository
2024-06-19T14:15:37.7800175Z [command]/usr/bin/git init /home/runner/work/fractal-server/fractal-server
2024-06-19T14:15:37.7898852Z hint: Using 'master' as the name for the initial branch. This default branch name
2024-06-19T14:15:37.7901098Z hint: is subject to change. To configure the initial branch name to use in all
2024-06-19T14:15:37.7902614Z hint: of your new repositories, which will suppress this warning, call:
2024-06-19T14:15:37.7903355Z hint:
2024-06-19T14:15:37.7904017Z hint: 	git config --global init.defaultBranch <name>
2024-06-19T14:15:37.7904615Z hint:
2024-06-19T14:15:37.7905215Z hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
2024-06-19T14:15:37.7906528Z hint: 'development'. The just-created branch can be renamed via this command:
2024-06-19T14:15:37.7907562Z hint:
2024-06-19T14:15:37.7907938Z hint: 	git branch -m <name>
2024-06-19T14:15:37.7908922Z Initialized empty Git repository in /home/runner/work/fractal-server/fractal-server/.git/
2024-06-19T14:15:37.7912487Z [command]/usr/bin/git remote add origin https://github.com/fractal-analytics-platform/fractal-server
2024-06-19T14:15:37.7948535Z ##[endgroup]
2024-06-19T14:15:37.7949295Z ##[group]Disabling automatic garbage collection
2024-06-19T14:15:37.7952463Z [command]/usr/bin/git config --local gc.auto 0
2024-06-19T14:15:37.7982905Z ##[endgroup]
2024-06-19T14:15:37.7983707Z ##[group]Setting up auth
2024-06-19T14:15:37.7989690Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2024-06-19T14:15:37.8021455Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2024-06-19T14:15:37.8335023Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2024-06-19T14:15:37.8365317Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2024-06-19T14:15:37.8621170Z [command]/usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
2024-06-19T14:15:37.8658263Z ##[endgroup]
2024-06-19T14:15:37.8659424Z ##[group]Fetching the repository
2024-06-19T14:15:37.8666711Z [command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +e233bd6daabafa82f54991d072d0b8fcc73bee15:refs/remotes/pull/1545/merge
2024-06-19T14:15:38.3420471Z From https://github.com/fractal-analytics-platform/fractal-server
2024-06-19T14:15:38.3422096Z  * [new ref]         e233bd6daabafa82f54991d072d0b8fcc73bee15 -> pull/1545/merge
2024-06-19T14:15:38.3443313Z ##[endgroup]
2024-06-19T14:15:38.3444571Z ##[group]Determining the checkout info
2024-06-19T14:15:38.3445874Z ##[endgroup]
2024-06-19T14:15:38.3451804Z [command]/usr/bin/git sparse-checkout disable
2024-06-19T14:15:38.3496312Z [command]/usr/bin/git config --local --unset-all extensions.worktreeConfig
2024-06-19T14:15:38.3526692Z ##[group]Checking out the ref
2024-06-19T14:15:38.3531222Z [command]/usr/bin/git checkout --progress --force refs/remotes/pull/1545/merge
2024-06-19T14:15:38.4100436Z Note: switching to 'refs/remotes/pull/1545/merge'.
2024-06-19T14:15:38.4101118Z 
2024-06-19T14:15:38.4101643Z You are in 'detached HEAD' state. You can look around, make experimental
2024-06-19T14:15:38.4102665Z changes and commit them, and you can discard any commits you make in this
2024-06-19T14:15:38.4103841Z state without impacting any branches by switching back to a branch.
2024-06-19T14:15:38.4104399Z 
2024-06-19T14:15:38.4104785Z If you want to create a new branch to retain commits you create, you may
2024-06-19T14:15:38.4105797Z do so (now or later) by using -c with the switch command. Example:
2024-06-19T14:15:38.4106393Z 
2024-06-19T14:15:38.4106683Z   git switch -c <new-branch-name>
2024-06-19T14:15:38.4107020Z 
2024-06-19T14:15:38.4107265Z Or undo this operation with:
2024-06-19T14:15:38.4107566Z 
2024-06-19T14:15:38.4107725Z   git switch -
2024-06-19T14:15:38.4108297Z 
2024-06-19T14:15:38.4108929Z Turn off this advice by setting config variable advice.detachedHead to false
2024-06-19T14:15:38.4109798Z 
2024-06-19T14:15:38.4110354Z HEAD is now at e233bd6 Merge 4384e1b5cbb29bc26f897437f122bfcdfcb6378d into 1681b962465d32639e92b71efd1e73c1c730462b
2024-06-19T14:15:38.4112248Z ##[endgroup]
2024-06-19T14:15:38.4152866Z [command]/usr/bin/git log -1 --format='%H'
2024-06-19T14:15:38.4177461Z 'e233bd6daabafa82f54991d072d0b8fcc73bee15'
2024-06-19T14:15:38.4527178Z ##[group]Run actions/setup-python@v5
2024-06-19T14:15:38.4527788Z with:
2024-06-19T14:15:38.4528128Z   python-version: 3.10
2024-06-19T14:15:38.4528485Z   check-latest: false
2024-06-19T14:15:38.4529162Z   token: ***
2024-06-19T14:15:38.4529534Z   update-environment: true
2024-06-19T14:15:38.4529894Z   allow-prereleases: false
2024-06-19T14:15:38.4530359Z ##[endgroup]
2024-06-19T14:15:38.6100249Z ##[group]Installed versions
2024-06-19T14:15:38.6159887Z Successfully set up CPython (3.10.14)
2024-06-19T14:15:38.6161400Z ##[endgroup]
2024-06-19T14:15:38.6307014Z ##[group]Run curl -sSL https://install.python-poetry.org | python3 - --version 1.8.2
2024-06-19T14:15:38.6308247Z [36;1mcurl -sSL https://install.python-poetry.org | python3 - --version 1.8.2[0m
2024-06-19T14:15:38.6433825Z shell: /usr/bin/bash -e {0}
2024-06-19T14:15:38.6434273Z env:
2024-06-19T14:15:38.6434737Z   pythonLocation: /opt/hostedtoolcache/Python/3.10.14/x64
2024-06-19T14:15:38.6435487Z   PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.14/x64/lib/pkgconfig
2024-06-19T14:15:38.6436097Z   Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.14/x64
2024-06-19T14:15:38.6436720Z   Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.14/x64
2024-06-19T14:15:38.6437390Z   Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.14/x64
2024-06-19T14:15:38.6438007Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.14/x64/lib
2024-06-19T14:15:38.6438475Z ##[endgroup]
2024-06-19T14:15:52.7416787Z Retrieving Poetry metadata
2024-06-19T14:15:52.7417822Z 
2024-06-19T14:15:52.7418324Z # Welcome to Poetry!
2024-06-19T14:15:52.7420209Z 
2024-06-19T14:15:52.7421130Z This will download and install the latest version of Poetry,
2024-06-19T14:15:52.7422122Z a dependency and package manager for Python.
2024-06-19T14:15:52.7424732Z 
2024-06-19T14:15:52.7425948Z It will add the `poetry` command to Poetry's bin directory, located at:
2024-06-19T14:15:52.7426640Z 
2024-06-19T14:15:52.7427030Z /home/runner/.local/bin
2024-06-19T14:15:52.7428470Z 
2024-06-19T14:15:52.7429218Z You can uninstall at any time by executing this script with the --uninstall option,
2024-06-19T14:15:52.7431017Z and these changes will be reverted.
2024-06-19T14:15:52.7431505Z 
2024-06-19T14:15:52.7431741Z Installing Poetry (1.8.2)
2024-06-19T14:15:52.7432470Z Installing Poetry (1.8.2): Creating environment
2024-06-19T14:15:52.7433366Z Installing Poetry (1.8.2): Installing Poetry
2024-06-19T14:15:52.7434093Z Installing Poetry (1.8.2): Creating script
2024-06-19T14:15:52.7434822Z Installing Poetry (1.8.2): Done
2024-06-19T14:15:52.7435212Z 
2024-06-19T14:15:52.7435585Z Poetry (1.8.2) is installed now. Great!
2024-06-19T14:15:52.7436033Z 
2024-06-19T14:15:52.7436382Z You can test that everything is set up by executing:
2024-06-19T14:15:52.7436962Z 
2024-06-19T14:15:52.7437229Z `poetry --version`
2024-06-19T14:15:52.7437563Z 
2024-06-19T14:15:52.7585625Z ##[group]Run poetry build
2024-06-19T14:15:52.7586070Z [36;1mpoetry build[0m
2024-06-19T14:15:52.7648092Z shell: /usr/bin/bash -e {0}
2024-06-19T14:15:52.7648440Z env:
2024-06-19T14:15:52.7648979Z   pythonLocation: /opt/hostedtoolcache/Python/3.10.14/x64
2024-06-19T14:15:52.7649698Z   PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.14/x64/lib/pkgconfig
2024-06-19T14:15:52.7650293Z   Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.14/x64
2024-06-19T14:15:52.7650954Z   Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.14/x64
2024-06-19T14:15:52.7651524Z   Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.14/x64
2024-06-19T14:15:52.7652062Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.14/x64/lib
2024-06-19T14:15:52.7652647Z ##[endgroup]
2024-06-19T14:15:53.3463940Z Creating virtualenv fractal-server-21eqDTaF-py3.10 in /home/runner/.cache/pypoetry/virtualenvs
2024-06-19T14:15:53.3519558Z Exception ignored in: <function BaseFileLock.__del__ at 0x7fc6b2404670>
2024-06-19T14:15:53.3520730Z Traceback (most recent call last):
2024-06-19T14:15:53.3529560Z   File "/home/runner/.local/share/pypoetry/venv/lib/python3.10/site-packages/filelock/_api.py", line 388, in __del__
2024-06-19T14:15:53.3530576Z     self.release(force=True)
2024-06-19T14:15:53.3531693Z   File "/home/runner/.local/share/pypoetry/venv/lib/python3.10/site-packages/virtualenv/util/lock.py", line 34, in release
2024-06-19T14:15:53.3532502Z     with self.thread_safe:
2024-06-19T14:15:53.3533086Z AttributeError: '_CountedFileLock' object has no attribute 'thread_safe'
2024-06-19T14:15:53.3840930Z 
2024-06-19T14:15:53.3842126Z _CountedFileLock.__init__() got an unexpected keyword argument 'timeout'
2024-06-19T14:15:53.4378216Z ##[error]Process completed with exit code 1.
2024-06-19T14:15:53.4478763Z Post job cleanup.
2024-06-19T14:15:53.5410112Z [command]/usr/bin/git version
2024-06-19T14:15:53.5452789Z git version 2.45.2
2024-06-19T14:15:53.5493430Z Temporarily overriding HOME='/home/runner/work/_temp/938bd55f-d6d4-49a4-9b21-ea028e80c2ef' before making global git config changes
2024-06-19T14:15:53.5494826Z Adding repository directory to the temporary git global config as a safe directory
2024-06-19T14:15:53.5499633Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/fractal-server/fractal-server
2024-06-19T14:15:53.5533739Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2024-06-19T14:15:53.5566129Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2024-06-19T14:15:53.5813357Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2024-06-19T14:15:53.5835545Z http.https://github.com/.extraheader
2024-06-19T14:15:53.5847634Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2024-06-19T14:15:53.5881300Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2024-06-19T14:15:53.6340923Z Cleaning up orphan processes
```

**Comment by tcompa** [comment]
Not happening
