### ISSUE TITLE
Make sure that the whole `FractalSSHSlurmExecutor._completion` method is whitin a `try/except` block

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1962]
Thanks @fdsteffen for reporting this issue!

# Description

1. A job is running, on a SLURM/SSH Fractal instance

2. At some point, the SLURM job ends (successfully).
This is clearly visible in the logs, which report the output of `squeue` for that specific job as `COMPLETED`
```
 2024-10-23 18:17:08,982 - fractal_server.ssh._fabric - INFO - [attempt 1/5] START running 'squeue --noheader --format='%i %T' --jobs 17583618 --states=all' over SSH.
 2024-10-23 18:17:08,982 - fractal_server.ssh._fabric - INFO - Trying to acquire lock for 'run squeue --noheader --format='%i %T' --jobs 17583618 --states=all', with timeout=250
 2024-10-23 18:17:08,982 - fractal_server.ssh._fabric - INFO - Lock for 'run squeue --noheader --format='%i %T' --jobs 17583618 --states=all' was acquired.
 2024-10-23 18:17:09,015 - fractal_server.ssh._fabric - INFO - Lock for 'run squeue --noheader --format='%i %T' --jobs 17583618 --states=all' was released.
 2024-10-23 18:17:09,015 - fractal_server.ssh._fabric - INFO - [attempt 1/5] END   running 'squeue --noheader --format='%i %T' --jobs 17583618 --states=all' over SSH, elapsed 0.034
 2024-10-23 18:17:09,015 - fractal_server.ssh._fabric - DEBUG - STDOUT: 17583618 COMPLETED
```

3. This triggers the execution of the `FractalSSHSlurmExecutor._completion` callback. This function _does not_ run on the main thread where the `FractalSSHSlurmExecutor` was created, but rather on `FractalSSHSlurmExecutor.wait_thread`. Exceptions from this thread are not raised, see the following block (where `callback` is `FractalSSHSlurmExecutor._completion`):
https://github.com/fractal-analytics-platform/fractal-server/blob/9491278a144977e1f16af6bc913d5d0909801c21/fractal_server/app/runner/executors/slurm/ssh/_executor_wait_thread.py#L71-L87

4. An exception in `FractalSSHSlurmExecutor._completion` takes place (we don't know the reason, but that's a different question).
```python traceback
 2024-10-23 18:17:09,070 - fractal_server.ssh._fabric - INFO - [attempt 1/5] START running '/remote/fractal-server-env/bin/python -m fractal_server.app.runner.compress_folder /remote/jobs/proj_v2_0000006_wf_0000009_job_0000017_20241023_180255/0_harmony_to_ome_zarr --remote-to-local' over SSH.
 2024-10-23 18:17:09,070 - fractal_server.ssh._fabric - INFO - Trying to acquire lock for 'run /remote/fractal-server-env/bin/python -m fractal_server.app.runner.compress_folder /remote/jobs/proj_v2_0000006_wf_0000009_job_0000017_20241023_180255/0_harmony_to_ome_zarr --remote-to-local', with timeout=250
 2024-10-23 18:17:09,070 - fractal_server.ssh._fabric - INFO - Lock for 'run /remote/fractal-server-env/bin/python -m fractal_server.app.runner.compress_folder /remote/jobs/proj_v2_0000006_wf_0000009_job_0000017_20241023_180255/0_harmony_to_ome_zarr --remote-to-local' was acquired.
 2024-10-23 18:17:24,271 - fractal_server.ssh._fabric - INFO - Lock for 'run /remote/fractal-server-env/bin/python -m fractal_server.app.runner.compress_folder /remote/jobs/proj_v2_0000006_wf_0000009_job_0000017_20241023_180255/0_harmony_to_ome_zarr --remote-to-local' was released.
 2024-10-23 18:17:24,271 - fractal_server.ssh._fabric - ERROR - [attempt 1/5] Running command `/remote/fractal-server-env/bin/python -m fractal_server.app.runner.compress_folder /remote/jobs/proj_v2_0000006_wf_0000009_job_0000017_20241023_180255/0_harmony_to_ome_zarr --remote-to-local` over SSH failed.
 Original error:
 Encountered a bad command exit code!
 Command: '/remote/fractal-server-env/bin/python -m fractal_server.app.runner.compress_folder /remote/jobs/proj_v2_0000006_wf_0000009_job_0000017_20241023_180255/0_harmony_to_ome_zarr --remote-to-local'
 Exit code: 1
 Stdout:
 Stderr:
 .
 Traceback (most recent call last):
   File "/local/venv/lib/python3.10/site-packages/fractal_server/ssh/_fabric.py", line 280, in run_command
     res = self._run(
   File "/local/venv/lib/python3.10/site-packages/fractal_server/ssh/_fabric.py", line 174, in _run
     return self._connection.run(*args, **kwargs)
   File "/local/venv/lib/python3.10/site-packages/decorator.py", line 232, in fun
     return caller(func, *(extras + args), **kw)
   File "/local/venv/lib/python3.10/site-packages/fabric/connection.py", line 23, in opens
     return method(self, *args, **kwargs)
   File "/local/venv/lib/python3.10/site-packages/fabric/connection.py", line 763, in run
     return self._run(self._remote_runner(), command, **kwargs)
   File "/local/venv/lib/python3.10/site-packages/invoke/context.py", line 113, in _run
     return runner.run(command, **kwargs)
   File "/local/venv/lib/python3.10/site-packages/fabric/runners.py", line 83, in run
     return super().run(command, **kwargs)
   File "/local/venv/lib/python3.10/site-packages/invoke/runners.py", line 395, in run
     return self._run_body(command, **kwargs)
   File "/local/venv/lib/python3.10/site-packages/invoke/runners.py", line 451, in _run_body
     return self.make_promise() if self._asynchronous else self._finish()
   File "/local/venv/lib/python3.10/site-packages/invoke/runners.py", line 518, in _finish
     raise UnexpectedExit(result)
 invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
 Command: '/remote/fractal-server-env/bin/python -m fractal_server.app.runner.compress_folder /remote/jobs/proj_v2_0000006_wf_0000009_job_0000017_20241023_180255/0_harmony_to_ome_zarr --remote-to-local'
 Exit code: 1
 Stdout:
 Stderr:
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
   File "/local/venv/lib/python3.10/site-packages/fractal_server/app/runner/executors/slurm/ssh/_executor_wait_thread.py", line 82, in check_jobs
     self.callback(self.active_job_ids)
   File "/local/venv/lib/python3.10/site-packages/fractal_server/app/runner/executors/slurm/ssh/executor.py", line 1072, in _completion
     self._get_subfolder_sftp(jobs=jobs)
   File "/local/venv/lib/python3.10/site-packages/fractal_server/app/runner/executors/slurm/ssh/executor.py", line 1269, in _get_subfolder_sftp
     stdout = self.fractal_ssh.run_command(cmd=tar_command)
   File "/local/venv/lib/python3.10/site-packages/fractal_server/ssh/_fabric.py", line 318, in run_command
     raise RuntimeError(error_msg)
 RuntimeError: [attempt 1/5] Running command `/remote/fractal-server-env/bin/python -m fractal_server.app.runner.compress_folder /remote/jobs/proj_v2_0000006_wf_0000009_job_0000017_20241023_180255/0_harmony_to_ome_zarr --remote-to-local` over SSH failed.
 Original error:
 Encountered a bad command exit code!
 Command: '/remote/fractal-server-env/bin/python -m fractal_server.app.runner.compress_folder /remote/jobs/proj_v2_0000006_wf_0000009_job_0000017_20241023_180255/0_harmony_to_ome_zarr --remote-to-local'
 Exit code: 1
 Stdout:
 Stderr:
 .
```

5. We do see the exception traceback (due to the `traceback.print_exc()` in the previous code block), but this is not handled in any way. And the job was not marked as "failed".

6. From now on, the job is still marked as submitted and the executor keeps going, but it won't be able to work as expected. For instance it will report errors like
```python traceback
 2024-10-23 18:19:14,846 - fractal_server.app.runner.executors.slurm.ssh.executor - DEBUG - [FractalSlurmSSHExecutor._jobs_finished] END - output={'17583618'}
 Traceback (most recent call last):
   File "/local/venv/lib/python3.10/site-packages/fractal_server/app/runner/executors/slurm/ssh/_executor_wait_thread.py", line 82, in check_jobs
     self.callback(self.active_job_ids)
   File "/local/venv/lib/python3.10/site-packages/fractal_server/app/runner/executors/slurm/ssh/executor.py", line 1064, in _completion
     future, job = self.jobs.pop(job_id)
 KeyError: '17583618'
```

**Comment by tcompa** [comment]
# How to fix

For the sudo/SLURM executor, we have the same situation (with the waiting thread calling the callback), and we made `_completion` safer to use through a global `try/except` block (note the docstring):

https://github.com/fractal-analytics-platform/fractal-server/blob/9491278a144977e1f16af6bc913d5d0909801c21/fractal_server/app/runner/executors/slurm/sudo/executor.py#L811-L826

https://github.com/fractal-analytics-platform/fractal-server/blob/9491278a144977e1f16af6bc913d5d0909801c21/fractal_server/app/runner/executors/slurm/sudo/executor.py#L981-L990

The same approach should be done also for the SSH/SLURM, which is currently not protected by a global `try/except` block:
https://github.com/fractal-analytics-platform/fractal-server/blob/9491278a144977e1f16af6bc913d5d0909801c21/fractal_server/app/runner/executors/slurm/ssh/executor.py#L1044-L1229
