### ISSUE TITLE
AttributeError: type object 'DB' has no attribute '_async_session_maker'

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#206]
```python traceback
INFO:     127.0.0.1:56046 - "POST /auth/token/login HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/fastapi/routing.py", line 217, in app
    solved_result = await solve_dependencies(
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 500, in solve_dependencies
    solved_result = await solve_dependencies(
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 500, in solve_dependencies
    solved_result = await solve_dependencies(
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 525, in solve_dependencies
    solved = await solve_generator(
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 449, in solve_generator
    return await stack.enter_async_context(cm)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/contextlib.py", line 568, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/fractal-server/fractal_server/app/db/__init__.py", line 59, in get_db
    async with cls._async_session_maker() as async_session:
AttributeError: type object 'DB' has no attribute '_async_session_maker'
```

**Comment by tcompa** [comment]
Patch:
```

diff --git a/examples/server/fractal_server/migrations/env.py b/examples/server/fractal_server/migrations/env.py
index 093d0b1..60188ed 100644
--- a/examples/server/fractal_server/migrations/env.py
+++ b/examples/server/fractal_server/migrations/env.py
@@ -6,7 +6,8 @@ from sqlalchemy.engine import Connection
 from sqlmodel import SQLModel
 
 from fractal_server.app import models  # noqa
-from fractal_server.config import settings
+from fractal_server.config import get_settings
+from fractal_server.syringe import Inject
 
 # this is the Alembic Config object, which provides
 # access to the values within the .ini file in use.
@@ -41,6 +42,7 @@ def run_migrations_offline() -> None:
     script output.
 
     """
+    settings = Inject(get_settings)
     context.configure(
         url=settings.DATABASE_URL,
         target_metadata=target_metadata,
@@ -66,8 +68,9 @@ async def run_migrations_online() -> None:
     and associate a connection with the context.
 
     """
-    from fractal_server.app.db import engine
+    from fractal_server.app.db import DB
 
+    engine = DB.engine_async()
     async with engine.connect() as connection:
         await connection.run_sync(do_run_migrations)
```
