### ISSUE TITLE
Fail for `add-task` if `task_id` does not exist

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#225]
After creating a workflow (via the client), issuing `fractal workflow add-task 1 1` gives a non-informative error:
```
$ fractal workflow add-task 1 1

DEBUG:asyncio:Using selector: EpollSelector
DEBUG:root:Namespace(batch=False, cmd='workflow', id='1', json=False, order=None, password=None, slurm_user=None, subcmd='add-task', task_id='1', user=None, v=0)
DEBUG:httpx._client:HTTP Request: POST http://localhost:8002/api/v1/workflow/1/add-task/ "HTTP/1.1 500 Internal Server Error"
DEBUG:root:500
ERROR:root:Server returned 500
ERROR:root:Original request: POST http://localhost:8002/api/v1/workflow/1/add-task/
ERROR:root:Original payload: {"workflow_id": null, "task_id": 1, "order": null, "args": null}
ERROR:root:Server error message: {}

ERROR:root:Terminating.
```

The error in the server logs read
```python traceback
INFO:     127.0.0.1:36730 - "POST /api/v1/workflow/1/add-task/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fastapi/routing.py", line 235, in app
    response_data = await serialize_response(
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fastapi/routing.py", line 138, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for WorkflowRead
response -> task_list -> 0 -> task
  none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by tcompa** [comment]
(ongoing debugging)

This is the `new_task` which is used in the `add-task` endpoint (notice that `workflow_id=None`):

```
/home/tommaso/miniconda3/envs/fractal-server-v1/lib/python3.8/site-packages/fractal_server/app/api/v1/workflow.py:137 add_task_to_workflow
    new_task: WorkflowTaskCreate(
        workflow_id=None,
        task_id=1,
        order=None,
        args=None,
    )
```

**Comment by tcompa** [comment]
This was probably a client error: https://github.com/fractal-analytics-platform/fractal/issues/311

(still, we should fail gracefully)

**Comment by tcompa** [comment]
Not sure of whether the error is on the server or client side. It appears only when one of the attributes of 
```
    new_task: WorkflowTaskCreate(
        workflow_id=1,
        task_id=1,
        order=1,
        args={},
    ) (WorkflowTaskCreate)
```
is `None`, while everything runs smoothly if the arguments are all there. Who's responsible for this check? Server or client? @jacopo-exact

**Comment by tcompa** [comment]
For the record: the error here was that the task collection had not completed.

Still to fix: why doesn't the `db.commit()` in `insert_task` fail?

**Comment by jacopo-exact** [comment]
SQLite does not enforce foreign key constraints unless explicitly instructed to do so.

**Comment by jacopo-exact** [comment]
this issue was superseded by PR #241.

We are offering only limited support to sqlite because of its intrinsic limitations. It should be considered a development db engine but production deployment should take place in postgres (the only supported db so far).
