### ISSUE TITLE
`project/apply` triggers `AttributeError: type object 'Project' has no attribute 'user_owner_id'`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#228]
Client-side
```python traceback
$ fractal workflow apply -o $DS_OUT_ID -p $PRJ_ID $WF_ID $DS_IN_ID
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:root:Namespace(batch=False, cmd='workflow', input_dataset_id='3', json=False, output_dataset_id='4', overwrite_input=False, password=None, project_id='2', slurm_user=None, subcmd='apply', user=None, v=0, workflow_id='2')
DEBUG:httpx._client:HTTP Request: POST http://localhost:8002/api/v1/project/apply/ "HTTP/1.1 500 Internal Server Error"
Traceback (most recent call last):
  File "/data/homes/test01/.conda/envs/fractal-client-v1/bin/fractal", line 8, in <module>
    sys.exit(run())
  File "/data/homes/test01/.conda/envs/fractal-client-v1/lib/python3.8/site-packages/fractal/__main__.py", line 7, in run
    asyncio.run(main())
  File "/data/homes/test01/.conda/envs/fractal-client-v1/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/data/homes/test01/.conda/envs/fractal-client-v1/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/data/homes/test01/.conda/envs/fractal-client-v1/lib/python3.8/site-packages/fractal/client/client.py", line 65, in main
    interface = await handle()
  File "/data/homes/test01/.conda/envs/fractal-client-v1/lib/python3.8/site-packages/fractal/client/client.py", line 55, in handle
    interface = await handler(client, **vars(args))
  File "/data/homes/test01/.conda/envs/fractal-client-v1/lib/python3.8/site-packages/fractal/client/cmd/__init__.py", line 161, in workflow
    iface = await workflow_apply(client, **kwargs)
  File "/data/homes/test01/.conda/envs/fractal-client-v1/lib/python3.8/site-packages/fractal/client/cmd/_workflow.py", line 151, in workflow_apply
    return RichJsonInterface(retcode=0, data=res.json())
  File "/data/homes/test01/.conda/envs/fractal-client-v1/lib/python3.8/site-packages/httpx/_models.py", line 743, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/data/homes/test01/.conda/envs/fractal-client-v1/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/data/homes/test01/.conda/envs/fractal-client-v1/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/homes/test01/.conda/envs/fractal-client-v1/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Server-side
```python traceback
INFO:     127.0.0.1:45534 - "POST /api/v1/project/apply/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/fractal-server/fractal_server/app/api/v1/project.py", line 177, in apply_workflow
    .where(Project.user_owner_id == user.id)
AttributeError: type object 'Project' has no attribute 'user_owner_id'

```

**Comment by tcompa** [comment]
This is probably a problem with a wrong environment. I'm taking care of it.

**Comment by jacopo-exact** [comment]
you are using a legacy v0.x version.
this is already fixed and aligned in v1.

**Comment by tcompa** [comment]
I confirm. Closing.
