### ISSUE TITLE
Better handling of task-collection error when folder already exists

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#234]
There are two cases:
* The folder exists, but for the wrong reasons (e.g. collection failed, and `collection.json` is missing or corrupt) and it is not to be used.
* The folder exists, and it is a valid task folder (e.g. the collection had already been triggered by another user).

At the moment, the error traceback is just
```python traceback
Traceback (most recent call last):
  File "/home/tommaso/miniconda3/envs/fractal-client-v1/bin/fractal", line 8, in <module>
    sys.exit(run())
  File "/home/tommaso/miniconda3/envs/fractal-client-v1/lib/python3.8/site-packages/fractal/__main__.py", line 7, in run
    asyncio.run(main())
  File "/home/tommaso/miniconda3/envs/fractal-client-v1/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/tommaso/miniconda3/envs/fractal-client-v1/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/tommaso/miniconda3/envs/fractal-client-v1/lib/python3.8/site-packages/fractal/client/client.py", line 65, in main
    interface = await handle()
  File "/home/tommaso/miniconda3/envs/fractal-client-v1/lib/python3.8/site-packages/fractal/client/client.py", line 55, in handle
    interface = await handler(client, **vars(args))
  File "/home/tommaso/miniconda3/envs/fractal-client-v1/lib/python3.8/site-packages/fractal/client/cmd/__init__.py", line 139, in task
    iface = await task_collect_pip(client, batch=batch, **kwargs)
  File "/home/tommaso/miniconda3/envs/fractal-client-v1/lib/python3.8/site-packages/fractal/client/cmd/_task.py", line 104, in task_collect_pip
    raise RuntimeError(res.json())
RuntimeError: {'detail': "The package is already installed. Original error: [Errno 17] File exists: '/home/tommaso/Fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core'"}
```

I would expect a check on the existence `collection.json`, and then a warning like
```
The folder already exists, and this is the JSON of its tasks. Do what you like with this information.
```

**Comment by jacopo-exact** [comment]
if package already installed successfully, tell user how to access tasks and exit gracefully.
