### ISSUE TITLE
Permission denied errors, when running with different SLURM user

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#243]
This issue was expected, since we never tested V1 on a SLURM cluster and with users different from the fractal one.

The failing test is this one: https://github.com/fractal-analytics-platform/fractal-demos/tree/7a373dcbbef603f70f4fea2b1b2759b844d5e227/examples-v1.

The error tracebacks are reported below.

---

Task logs:
```python traceback
$ cat artifacts/workflow_000001/0.err 
2022-11-11 07:53:56,221; INFO; actual_channels: ['A01_C01']
2022-11-11 07:53:56,221; INFO; Creating 20200812-CardiomyocyteDifferentiation14-Cycle1.zarr
Traceback (most recent call last):
  File "/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core/venv/lib/python3.8/site-packages/zarr/storage.py", line 1095, in __setitem__
    os.makedirs(dir_path)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data/homes/test01/fractal-demos/examples-v1/01_cardio_tiny_dataset/tmp_4/output'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core/venv/lib/python3.8/site-packages/fractal_tasks_core/create_zarr_structure.py", line 438, in <module>
    run_fractal_task(
  File "/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core/venv/lib/python3.8/site-packages/fractal_tasks_core/_utils.py", line 80, in run_fractal_task
    metadata_update = task_function(**task_args.dict())
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core/venv/lib/python3.8/site-packages/fractal_tasks_core/create_zarr_structure.py", line 246, in create_zarr_structure
    group_plate = zarr.group(output_path.parent / zarrurl)
  File "/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core/venv/lib/python3.8/site-packages/zarr/hierarchy.py", line 1286, in group
    init_group(store, overwrite=overwrite, chunk_store=chunk_store,
  File "/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core/venv/lib/python3.8/site-packages/zarr/storage.py", line 633, in init_group
    _init_group_metadata(store=store, overwrite=overwrite, path=path,
  File "/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core/venv/lib/python3.8/site-packages/zarr/storage.py", line 696, in _init_group_metadata
    store[key] = store._metadata_class.encode_group_metadata(meta)  # type: ignore
  File "/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core/venv/lib/python3.8/site-packages/zarr/storage.py", line 1098, in __setitem__
    raise KeyError(key)
KeyError: '.zgroup'
```

Server logs
```python traceback
Traceback (most recent call last):
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/routing.py", line 68, in app
    await response(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/responses.py", line 165, in __call__
    await self.background()
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/background.py", line 43, in __call__
    await task()
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/background.py", line 26, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fractal_server/app/runner/__init__.py", line 101, in submit_workflow
    output_dataset.meta = await process_workflow(
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fractal_server/app/runner/_process/__init__.py", line 158, in process_workflow
    output_task_pars_fut = recursive_task_submission(
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fractal_server/app/runner/_process/__init__.py", line 122, in recursive_task_submission
    this_future = call_parallel_task(
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fractal_server/app/runner/_process/__init__.py", line 39, in call_parallel_task
    task_pars_depend = task_pars_depend_future.result()
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fractal_server/app/runner/_common.py", line 104, in call_single_task
    _call_command_wrapper(cmd, stdout=stdout_file, stderr=stderr_file)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fractal_server/app/runner/_common.py", line 45, in _call_command_wrapper
    raise TaskExecutionError(err)
fractal_server.app.runner._common.TaskExecutionError: 2022-11-11 07:53:56,221; INFO; actual_channels: ['A01_C01']
2022-11-11 07:53:56,221; INFO; Creating 20200812-CardiomyocyteDifferentiation14-Cycle1.zarr
Traceback (most recent call last):
  File "/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core/venv/lib/python3.8/site-packages/zarr/storage.py", line 1095, in __setitem__
    os.makedirs(dir_path)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data/homes/test01/fractal-demos/examples-v1/01_cardio_tiny_dataset/tmp_4/output'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core/venv/lib/python3.8/site-packages/fractal_tasks_core/create_zarr_structure.py", line 438, in <module>
    run_fractal_task(
  File "/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core/venv/lib/python3.8/site-packages/fractal_tasks_core/_utils.py", line 80, in run_fractal_task
    metadata_update = task_function(**task_args.dict())
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core/venv/lib/python3.8/site-packages/fractal_tasks_core/create_zarr_structure.py", line 246, in create_zarr_structure
    group_plate = zarr.group(output_path.parent / zarrurl)
  File "/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core/venv/lib/python3.8/site-packages/zarr/hierarchy.py", line 1286, in group
    init_group(store, overwrite=overwrite, chunk_store=chunk_store,
  File "/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core/venv/lib/python3.8/site-packages/zarr/storage.py", line 633, in init_group
    _init_group_metadata(store=store, overwrite=overwrite, path=path,
  File "/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core/venv/lib/python3.8/site-packages/zarr/storage.py", line 696, in _init_group_metadata
    store[key] = store._metadata_class.encode_group_metadata(meta)  # type: ignore
  File "/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core/venv/lib/python3.8/site-packages/zarr/storage.py", line 1098, in __setitem__
    raise KeyError(key)
KeyError: '.zgroup'
```

**Comment by tcompa** [comment]
Problem solved: the installation from wheel was not fetching parsl, and then task were being run as `fractal` user - who has no access to user folders.

(warning: I'm expecting other permission errors to pop up for the log folder, but not from within the task)

**Comment by tcompa** [comment]
This was fixed in the demo via https://github.com/fractal-analytics-platform/fractal-demos/commit/33c0c72e811efc8eec6178d06e414f0a7fd9e2ce
