### ISSUE TITLE
`FileNotFoundError` in SLURM backend execution

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#307]
Upon submission of a workflow through the SLURM backend, the server fails as in
```python traceback
Traceback (most recent call last):
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/routing.py", line 68, in app
    await response(scope, receive, send)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/responses.py", line 165, in __call__
    await self.background()
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/background.py", line 43, in __call__
    await task()
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/starlette/background.py", line 26, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fractal_server/app/runner/__init__.py", line 118, in submit_workflow
    output_dataset.meta = await process_workflow(
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fractal_server/app/runner/_slurm/__init__.py", line 181, in process_workflow
    output_dataset_metadata = await async_wrap(_process_workflow)(
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fractal_server/app/runner/common.py", line 127, in run
    return await loop.run_in_executor(executor, pfunc)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fractal_server/app/runner/_slurm/__init__.py", line 151, in _process_workflow
    output_task_pars_fut = recursive_task_submission(
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fractal_server/app/runner/_common.py", line 272, in recursive_task_submission
    task_pars_depend_future = recursive_task_submission(
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fractal_server/app/runner/_common.py", line 291, in recursive_task_submission
    this_future = executor.submit(
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fractal_server/app/runner/_slurm/executor.py", line 248, in submit
    jobid = self._start(workerid, additional_setup_lines)
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fractal_server/app/runner/_slurm/executor.py", line 307, in _start
    job_id = submit_sbatch(
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/site-packages/fractal_server/app/runner/_slurm/executor.py", line 99, in submit_sbatch
    output = subprocess.run(  # nosec
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/homes/fractal/.conda/envs/fractal-server-v1/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sudo --non-interactive -u test01 sbatch --parsable artifacts/_temp_hHQcPrQiVxIyXVbWTRVBp4zB4UXCaC3m.sh'
```

**Comment by jacopo-exact** [comment]
no such file or directory could also refer to the `sudo` or `sbatch` command, rather than the sbatch file.

**Comment by tcompa** [comment]
`artifacts` folder (with non-absolute path) is not visible to `test01` user
