### ISSUE TITLE
(tasks or server?) torch import error for gpu task

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#310]
While running a `cellpose_segmentation` task with server `1.0.0b1` and tasks `0.4.6`, we observe this error
```python traceback
$ cat 4_par_20200812-CardiomyocyteDifferentiation14-Cycle1_mip_zarr_B_03_0_.err 
/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/anndata/experimental/pytorch/_annloader.py:18: UserWarning: Сould not load pytorch.
  warnings.warn("Сould not load pytorch.")
Traceback (most recent call last):
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/fractal_tasks_core/cellpose_segmentation.py", line 35, in <module>
    from cellpose import models
  File "/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/cellpose/models.py", line 6, in <module>
    import torch
  File "/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/torch/__init__.py", line 202, in <module>
    from torch._C import *  # noqa: F403
ImportError: libtorch_cuda.so: failed to map segment from shared object
```

EDIT
Note that running the appropriate python interpreter (i.e. the one defined in the venv in `FRACTAL_ROOT`), the situation is as follows
```
Python 3.8.13 (default, Oct 21 2022, 23:50:54) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.12.1+cu102'
```

**Comment by jacopo-exact** [comment]
most likely task

**Comment by tcompa** [comment]
Possibly related to wrong configuration of SLURM, since I was assigning a very small memory requirement (1G) -- see https://github.com/pytorch/pytorch/issues/16558.

I will try to reproduce with larger memory requirement.

**Comment by tcompa** [comment]
Fixed by assigning larger memory, notably with this script:
```
#!/bin/sh
#SBATCH --output=/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/fractal-demos/examples-v1/server/artifacts/workflow_000001_job_000001/slurmpy.stdout.%j.log
#SBATCH --partition=gpu
#SBATCH --mem=61g
#SBATCH --nodes=1
#SBATCH --job-name Cellpose_Segmentation
export CFUT_DIR=/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/fractal-demos/examples-v1/server/artifacts/workflow_000001_job_000001
srun /data/homes/fractal/.conda/envs/fractal-server-v1/bin/python -m cfut.remote nt5Ym9PSu6NfeMp5CyT1Mw3wQG4awueC
```
