### ISSUE TITLE
Reinstate `WORKER_INIT` argument for workflow submission

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#312]
When running the cellpose-segmentation task, and after fixing #310, it still fails with
```python traceback
$ cat 4_par_20200812-CardiomyocyteDifferentiation14-Cycle1_mip_zarr_B_03_0_.err
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-mlqq0ii4 because the default path (/data/homes/fractal/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/fractal_tasks_core/cellpose_segmentation.py", line 35, in <module>
    from cellpose import models
  File "/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/cellpose/models.py", line 11, in <module>
    from . import transforms, dynamics, utils, plot
  File "/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/cellpose/transforms.py", line 9, in <module>
    from . import dynamics, utils
  File "/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/cellpose/dynamics.py", line 332, in <module>
    def map_coordinates(I, yc, xc, Y):
  File "/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/numba/core/decorators.py", line 212, in wrapper
    disp.enable_caching()
  File "/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/numba/core/dispatcher.py", line 863, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/numba/core/caching.py", line 601, in __init__
    self._impl = self._impl_class(py_func)
  File "/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/numba/core/caching.py", line 337, in __init__
    raise RuntimeError("cannot cache function %r: no locator available "
RuntimeError: cannot cache function 'map_coordinates': no locator available for file '/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/cellpose/dynamics.py'
```

**Comment by tcompa** [comment]
Still in progress, but for sure related to numba caching of functions.
Possible reasons:
* trying to write to a cache folder where the user does not have the right permissions,
* not having the correct environment variables (e.g. `NUMBA_CACHE_DIR`) set,
* other?

**Comment by tcompa** [comment]
First attempt: I'm making all directories in the venv `site-packages` folder fully visible/writeable:
```
$ ls -l FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/ | grep cellpose
drwxrwxrwx  7 fractal fractal     4096 Nov 28 14:41 cellpose
drwxrwxrwx  2 fractal fractal     4096 Nov 28 14:41 cellpose-2.1.1.dist-info
```
(this is achieved with a recursive `os.chmod(.., 0o777)` as in https://stackoverflow.com/a/2853934/19085332)

This fixes the error, and leads to a new one:

```
Traceback (most recent call last):
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/fractal_tasks_core/cellpose_segmentation.py", line 489, in <module>
    run_fractal_task(
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/fractal_tasks_core/_utils.py", line 89, in run_fractal_task
    metadata_update = task_function(**task_args.dict())
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/fractal_tasks_core/cellpose_segmentation.py", line 335, in cellpose_segmentation
    model = models.CellposeModel(gpu=gpu, model_type=model_type)
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/cellpose/models.py", line 369, in __init__
    self.net.load_model(self.pretrained_model[0], cpu=(not self.gpu))
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/cellpose/resnet_torch.py", line 222, in load_model
    state_dict = torch.load(filename)
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: '/data/homes/fractal/.cellpose/models/nucleitorch_0'
```

**Comment by tcompa** [comment]
Broader issue:
There exist some env variables for the task dependencies which are set to use paths which either belong to the `fractal` user or point (because they are not set) to a path which sits next to the python venv (then, again, in a `fractal`-owned directory).

Read access to these paths should be guaranteed, and also write access in some cases (e.g. numba caching). How would we proceed? Should we always export some user-specific env variables? How can we know which ones? Would switching back to `sudo su -` fix the issue?

**Comment by tcompa** [comment]
By the way, note the permissions in
```
$ ls -l /data/homes/fractal/.cellpose/models/
total 25948
-rw------- 1 fractal fractal 26563614 Jul 28 07:23 nucleitorch_0
-rw------- 1 fractal fractal     3627 Jul 28 07:23 size_nucleitorch_0.npy
```

**Comment by tcompa** [comment]
Question: does this information belong to `WorkflowTask.meta`?

**Comment by jluethi** [comment]
Oh, good that we're discovering those issues.

> Read access to these paths should be guaranteed, and also write access in some cases (e.g. numba caching). How would we proceed? Should we always export some user-specific env variables? How can we know which ones?

The more we can avoid having broad write access, the better. But at FMI, we now have a plan for a solution where there will be a (medium-sized) share that both the Fractal user and other users have read & write access to for logs & environments. So if there needs to be an env folder that users can write some things into, that is not perfect, but achievable.
If it would need to go to the home directory of the fractal user running the server: That likely won't be available on the FMI cluster (because we'll run the server from a separate VM that can submit to the cluster. But it has a local storage where it's home directory is and that won't be available on the nodes.

**Comment by tcompa** [comment]
> The more we can avoid having broad write access, the better.

I'm rather in favor of setting some env variables (which would go to some kind of `WORKER_INIT`) pointing to user-owned folders. Having all users writing their caches in some server folder doesn't look like the ideal solution.

The `WORKER_INIT` variable was there with the parsl backend, but it became unnecessary with the new slurm backend. We may have to reinstate it for the current issue.

**Comment by tcompa** [comment]
Re-opening as a placeholder, until we check it in the fractal-demo examples

**Comment by tcompa** [comment]
Now working with https://github.com/fractal-analytics-platform/fractal-demos/commit/a6ec6a8d86420febd2923f5b7a9744c4bcec1a1b. Closing.
