### ISSUE TITLE
Catch sudo permission issues

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#332]
When running in a new FMI setup, we ran into this error (I think the sudo setup wasn't correct yet). This only appears to show up in the server log. The user logs just contain the info that the workflow has been submitted.

Will this already be caught by catching the task errors (see https://github.com/fractal-analytics-platform/fractal-server/pull/327)? Because it fails at task submission. But would be good to also catch this!

```
sudo: PAM account management error: Permission denied

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/starlette/routing.py", line 68, in app
    await response(scope, receive, send)
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/starlette/responses.py", line 165, in __call__
    await self.background()
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/starlette/background.py", line 43, in __call__
    await task()
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/starlette/background.py", line 26, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/fractal_server/app/runner/__init__.py", line 113, in submit_workflow
    output_dataset.meta = await process_workflow(
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/fractal_server/app/runner/_slurm/__init__.py", line 189, in process_workflow
    output_dataset_metadata = await async_wrap(_process_workflow)(
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/fractal_server/app/runner/common.py", line 127, in run
    return await loop.run_in_executor(executor, pfunc)
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/fractal_server/app/runner/_slurm/__init__.py", line 161, in _process_workflow
    output_task_pars_fut = recursive_task_submission(
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/fractal_server/app/runner/_common.py", line 323, in recursive_task_submission
    task_pars_depend_future = recursive_task_submission(
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/fractal_server/app/runner/_common.py", line 323, in recursive_task_submission
    task_pars_depend_future = recursive_task_submission(
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/fractal_server/app/runner/_common.py", line 323, in recursive_task_submission
    task_pars_depend_future = recursive_task_submission(
  [Previous line repeated 1 more time]
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/fractal_server/app/runner/_common.py", line 341, in recursive_task_submission
    this_future = executor.submit(
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/fractal_server/app/runner/_slurm/executor.py", line 307, in submit
    jobid = self._start(job, additional_setup_lines)
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/fractal_server/app/runner/_slurm/executor.py", line 365, in _start
    job_id = self.submit_sbatch(
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/fractal_server/app/runner/_slurm/executor.py", line 150, in submit_sbatch
    raise e
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/site-packages/fractal_server/app/runner/_slurm/executor.py", line 143, in submit_sbatch
    output = subprocess.run(  # nosec
  File "/BASEPATH/fractal-server-v1-b3/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sudo', '--non-interactive', '-u', 'luetjoel', 'sbatch', '--parsable', '/PATH/fractal-logs/artifacts/workflow_000001_job_000001/0.slurm.JI3tUxU7Zh4cIqdHhnHQPv5huJdTZXlc.sbatch']' returned non-zero exit status 1.
```

(edited to remove base paths)

**Comment by jacopo-exact** [comment]
This error will be caught and written in the DB for further inspection.

closing as it will be solved as part of #106 (PR #327)
