### ISSUE TITLE
`ntasks-per-node>1` triggers multiple simultaneous executions of the remote worker

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#362]
I'm running a few tests in parallel at FMI and suddenly, I keep getting `zarr.errors.ContainsGroupError` at different places of workflows. Normally, we'd get this error if we didn't delete an old output file. I made sure that it's in fresh files though.
Very weirdly, this error occurs for different parts. Currently at FMI, I can reproducibly get the 01 example to fail at the parsing step with an error like this:
```
anding/fractal/fractal-envs/.fractal/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/utils.py", line 214, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/specs/registry.py", line 175, in write_elem
    _REGISTRY.get_writer(dest_type, t, modifiers)(f, k, elem, *args, **kwargs)
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/specs/registry.py", line 24, in wrapper
    result = func(g, k, *args, **kwargs)
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/specs/methods.py", line 279, in write_mapping
    g = f.create_group(k)
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/zarr/hierarchy.py", line 853, in create_group
    return self._write_op(self._create_group_nosync, name, overwrite=overwrite)
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/zarr/hierarchy.py", line 827, in _write_op
    return f(*args, **kwargs)
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/zarr/hierarchy.py", line 859, in _create_group_nosync
    init_group(self._store, path=path, chunk_store=self._chunk_store,
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/zarr/storage.py", line 633, in init_group
    _init_group_metadata(store=store, overwrite=overwrite, path=path,
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/zarr/storage.py", line 680, in _init_group_metadata
    raise ContainsGroupError(path)
zarr.errors.ContainsGroupError: path 'B/03/0/tables/well_ROI_table/varm' contains a group

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/create_ome_zarr.py", line 396, in <module>
    run_fractal_task(
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/_utils.py", line 104, in run_fractal_task
    metadata_update = task_function(**task_args.dict())
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/create_ome_zarr.py", line 361, in create_ome_zarr
    write_elem(group_tables, "well_ROI_table", well_ROIs_table)
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/utils.py", line 214, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/specs/registry.py", line 175, in write_elem
    _REGISTRY.get_writer(dest_type, t, modifiers)(f, k, elem, *args, **kwargs)
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/specs/registry.py", line 24, in wrapper
    result = func(g, k, *args, **kwargs)
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/specs/methods.py", line 221, in write_anndata
    write_elem(g, "varm", dict(adata.varm), dataset_kwargs=dataset_kwargs)
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/utils.py", line 220, in func_wrapper
    raise type(e)(
zarr.errors.ContainsGroupError: path "path 'B/03/0/tables/well_ROI_table/varm' contains a group\n\nAbove error raised while writing key 'varm' of <class 'zarr.hierarchy.Group'> to <zarr.storage.DirectoryStore object at 0x7fc539503df0>" contains a group
```

Sometimes this is varm part of the table, sometime this is var, sometimes obs.

And other workflows failed when building the cellpose pyramid with the same error. I don't currently understand what's happening here. Will try to reproduce this on the UZH side with example 01 next.

**Comment by tcompa** [comment]
If this is related to https://github.com/fractal-analytics-platform/fractal-server/pull/327 (likely), then 1.0.0b3 is the last working version.

**Comment by tcompa** [comment]
Some debugging instructions at UZH:
```
AS FRACTAL

cd /data/homes/fractal/tommaso/fractal-demos/examples-v1/275_debug/server
. Activate_conda.sh
. server_config_and_start.sh

AS TEST01
cd /data/homes/fractal/tommaso/fractal-demos/examples-v1/275_debug/client
. Activate_conda.sh
AFTER STARTING SERVER
. preliminary_setup.sh   # This collects tasks
# wait <1 minute
# check that `fractal task list` returns some tasks (two, actually)
. run_example.sh 1
. run_example.sh 2
. run_example.sh pippo

AS FRACTAL
Look at artifacts/workflow_000001_job_000001/, and especially at artifacts/workflow_000001_job_000001/0.err


NOTEs:
1. code in server/code_fractal_server/fractal_server/ is the one that runs the server (installed with pip -e)
2. We commented the statements removing the pickle in/out files, so that we will be able to inspect them further
```

**Comment by tcompa** [comment]
Note that the error trigger was the combination of:
* https://github.com/fractal-analytics-platform/fractal-server/pull/349,
* Using `cpu-mid` for the first task in the 01 example (which is useful exactly for this reason: testing),

**Comment by jluethi** [comment]
Oh, that would make a lot of sense! My workflows always failed at cpu-mid tasks! Thanks a lot for tracking this down! 👏🏻

**Comment by tcompa** [comment]
Re-opening, until we release and test again

**Comment by tcompa** [comment]
As of https://github.com/fractal-analytics-platform/fractal-demos/commit/0dd9e02a2c2ffebbbe8effdcdf7f72db48e69c3c, the example 01 in fractal-demos works as expected.

**Comment by jluethi** [comment]
Just confirming: Ran example 01 5x in parallel now on UZH servers with server 1.0.0b7 and they all completed successfully :) 

Great work tracking this down so fast @tcompa & @mfranzon ! 👏🏻
