### ISSUE TITLE
Raising errors from a different thread (e.g. `executor.FileWaitThread`)

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#366]
1. Case 1: a SLURM job fails for task-unrelated reasons (typical examples: out-of-memory kill by SLURM, or timeout, or even a `scancel`). As of https://github.com/fractal-analytics-platform/fractal-server/issues/343, we will capture and re-raise this error.
2. Case 2 (somewhat artificial, just for testing): the cloudpickle output file is created but it's corrupted, or its content is invalid for whatever reason.

These errors take place in the `FileWaitThread` thread attribute of the `FractalSlurmExecutor` (inheriting from the SlurmeExectutor of cfut, see [here](https://github.com/sampsyo/clusterfutures/blob/master/cfut/__init__.py)), either directly within `FileWaitThread.run()` or in its `callback` function.

How do we propagate those errors to the main thread, so that they can be transformed in a `TaskExecutionError` (or similar)?

---

Here is a minimal non-working example
```python
import threading
import time
import logging


class worker_thread(threading.Thread):
    def run(self):
        for i in range(2):
            logging.warning(f"Logging from worker_thread, {i}-th iteration")
            time.sleep(1)
        logging.warning("worker_thread will now raise")
        raise RuntimeError("this is an error")


class main_thread():
    def __init__(self):
        t = worker_thread()
        t.start()
        time.sleep(0.5)   # this is just to get nicer output, with separated main/worker logs
        for i in range(5):
            print()
            logging.warning(f"Logging from main_thread, {i}-th iteration")
            logging.warning(f"  Is worker_thread alive? {bool(t.is_alive())}")
            time.sleep(1)

main_thread()
```
with output
```
WARNING:root:Logging from worker_thread, 0-th iteration

WARNING:root:Logging from main_thread, 0-th iteration
WARNING:root:  Is worker_thread alive? True
WARNING:root:Logging from worker_thread, 1-th iteration

WARNING:root:Logging from main_thread, 1-th iteration
WARNING:root:  Is worker_thread alive? True
WARNING:root:worker_thread will now raise
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/tommaso/Fractal/test_threads/mnwe.py", line 12, in run
    raise RuntimeError("this is an error")
RuntimeError: this is an error

WARNING:root:Logging from main_thread, 2-th iteration
WARNING:root:  Is worker_thread alive? False

WARNING:root:Logging from main_thread, 3-th iteration
WARNING:root:  Is worker_thread alive? False

WARNING:root:Logging from main_thread, 4-th iteration
WARNING:root:  Is worker_thread alive? False
```

Possibly useful references:
* https://docs.python.org/dev/library/threading.html#threading.excepthook: We can use this to handle uncaught exceptions in threads, but we are not (yet?) able to use it to re-raise.
* https://docs.python.org/dev/library/threading.html#event-objects: We can add an `Event` attribute to the `FractalSlurmExecutor` (in the same way as there is a `FileWaitThread` attribute), and `set()` it when exceptions take place in the `FileWaitThread`, but how would we check for these exceptions in the main thread?
* ...

**Comment by tcompa** [comment]
Very relevant discussion and PR:
* https://github.com/sampsyo/clusterfutures/issues/18
* https://github.com/sampsyo/clusterfutures/pull/19

**Comment by tcompa** [comment]
Closing since the proof-of-principle in https://github.com/fractal-analytics-platform/fractal-server/pull/367 already worked through other means.
