### ISSUE TITLE
Make submit_workflow an actual background_task, in CI

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#435]
In the CI, the POST request to apply a workflow is blocking, and only returns when the workflow is complete/failed.

**Comment by tcompa** [comment]
Ref:
* https://stackoverflow.com/questions/67599119/fastapi-asynchronous-background-tasks-blocks-other-requests

(this may be an actual issue, and not just a CI one)

**Comment by tcompa** [comment]
Refs:
* https://github.com/tiangolo/fastapi/issues/3859
* https://github.com/encode/starlette/issues/919

**Comment by tcompa** [comment]
Better minimal-failing example:

```
$ cat main.py 
from fastapi import FastAPI
from fastapi import BackgroundTasks
import logging
import time

app = FastAPI()

async def long_wait(sleep_time):
    logging.warning(f"[long_wait] {time.perf_counter()=}")
    time.sleep(sleep_time)
    logging.warning(f"[long_wait] {time.perf_counter()=}")

@app.get("/")
async def root(background_tasks: BackgroundTasks):
    logging.warning(f"[root] {time.perf_counter()=}")
    background_tasks.add_task(long_wait, 3)
    logging.warning(f"[root] {time.perf_counter()=}")


$ cat client.py 
from httpx import AsyncClient
import asyncio
import time
from devtools import debug
from main import app


async def main():
    async with AsyncClient(app=app, base_url="http://127.0.0.1:8000") as client:
        t0 = time.perf_counter()
        response = await client.get("/")
        elapsed = time.perf_counter() - t0
        debug(elapsed)
        assert elapsed < 2

if __name__ == "__main__":
    asyncio.run(main())
```

```
$ uvicorn main:app
```

```
$ python client.py 
WARNING:root:[root] time.perf_counter()=26751.26441107
WARNING:root:[root] time.perf_counter()=26751.264505151
WARNING:root:[long_wait] time.perf_counter()=26751.264569276
WARNING:root:[long_wait] time.perf_counter()=26754.278305415
client.py:13 main
    elapsed: 3.0151649810031813 (float)
Traceback (most recent call last):
  File "/home/tommaso/Fractal/test_async_apply/client.py", line 17, in <module>
    asyncio.run(main())
  File "/home/tommaso/miniconda3/envs/test/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/tommaso/miniconda3/envs/test/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/tommaso/Fractal/test_async_apply/client.py", line 14, in main
    assert elapsed < 2
AssertionError
```

**Comment by tcompa** [comment]
It was indeed a CI-only issue. To do:
- [ ] Write some detail here and close.

**Comment by tcompa** [comment]
The issue here is that the CI client is attached to a specific app, because there is no actual server running. This somehow makes the client calls blocking. In the actual fractal-client, the client is not attached to a given app; rather, it simply communicates with the server address.

Closing.
