### ISSUE TITLE
Include more configuration checks at server startup

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#476]
With https://github.com/fractal-analytics-platform/fractal-server/pull/469 we introduced a first custom (i.e. different from a pydantic validation, raising ValidationErrors) check of configuration settings, namely to verify that if `FRACTAL_RUNNER_MAX_TASKS_PER_WORKFLOW` is defined then it must be an integer number larger than 0.

This kind of checks are very valuable, since they anticipate possible failures to server startup, rather than taking place (e.g.) in some endpoint or even in the backend runner.

This is backlog reminder issue: let's review config settings, and see whether other checks are reasonable at the very beginning (random example: if we are using slurm backend, let's check that the slurm-config file exists and let's check that `shutil.which("sbatch")` returns a path).

Meanwhile, as soon as we find a configuration error popping up downstream, let's see whether there is a way to catch it right away at server startup.

**Comment by tcompa** [comment]
As part of the ongoing PR #529, if one sets `FRACTAL_RUNNER_BACKEND=slurm` in the environment variables or file, but then tries to run fractal-server on a local machine, they will see something like
```python traceback
INFO:     Started server process [153420]
INFO:     Waiting for application startup.
/home/tommaso/Fractal/fractal-server/fractal_server/app/db/__init__.py:45: UserWarning: SQLite is partially supported but discouraged in production environment.SQLite offers partial support for ForeignKey constraints. As such, consistency of the database cannot be guaranteed.
  warn(
ERROR:    Traceback (most recent call last):
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 648, in startup
    await handler()
  File "/home/tommaso/Fractal/fractal-server/fractal_server/main.py", line 167, in on_startup
    await __on_startup()
  File "/home/tommaso/Fractal/fractal-server/fractal_server/main.py", line 75, in __on_startup
    check_settings()
  File "/home/tommaso/Fractal/fractal-server/fractal_server/main.py", line 65, in check_settings
    settings.check()
  File "/home/tommaso/Fractal/fractal-server/fractal_server/config.py", line 361, in check
    raise FractalConfigurationError(
fractal_server.config.FractalConfigurationError: FRACTAL_RUNNER_BACKEND=slurm but sbatch command not found.

ERROR:    Application startup failed. Exiting.
```
