### ISSUE TITLE
Failing gracefully when user fileshare runs out of space

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#492]
Currently, when the user fileshare runs out of space, the tasks fail (with errors like the one below), but the server keeps the job status at "running".

Possible that the user isn't writing the slurm output files correctly anymore in this state. Is there a way we can detect this and have the server also show the pipeline as failed with a relevant error? We see the following on the running server when looking at what it prints to console:

```
Exception in thread Thread-234:

Traceback (most recent call last):

File "/data/homes/fractal/.conda/envs/fractal-server-1.0.2/lib/python3.8/site-packages/fractal_server/app/runner/_slurm/executor.py", line 449, in _completion

fut.set_result(output)

File "/data/homes/fractal/.conda/envs/fractal-server-1.0.2/lib/python3.8/concurrent/futures/_base.py", line 532, in set_result

raise InvalidStateError('{}: {!r}'.format(self._state, self))

concurrent.futures._base.InvalidStateError: CANCELLED: <Future at 0x7f7c91fa0490 state=cancelled>
```

Example error for out of storage space for the task:
```
File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.0/venv/lib/python3.8/site-packages/zarr/core.py", line 1772, in _set_basic_selection_nd
self._set_selection(indexer, value, fields=fields)
File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.0/venv/lib/python3.8/site-packages/zarr/core.py", line 1824, in _set_selection
self._chunk_setitem(chunk_coords, chunk_selection, chunk_value, fields=fields)
File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.0/venv/lib/python3.8/site-packages/zarr/core.py", line 2089, in _chunk_setitem
self._chunk_setitem_nosync(chunk_coords, chunk_selection, value,
File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.0/venv/lib/python3.8/site-packages/zarr/core.py", line 2100, in _chunk_setitem_nosync
self.chunk_store[ckey] = self._encode_chunk(cdata)
File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.0/venv/lib/python3.8/site-packages/zarr/storage.py", line 1113, in setitem
self._tofile(value, temp_path)
File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.0/venv/lib/python3.8/site-packages/zarr/storage.py", line 1074, in _tofile
f.write(a)
OSError: [Errno 28] No space left on device
```

**Comment by tcompa** [comment]
Thanks, we'll look into this. In principle, when the the clusterfuture remote worker (the one that the user runs on the computing node, via SLURM) fails to write its output pickle file and (after a certain time interval) the job is not in SLURM squeue any more, then we raise a JobExecutionError. But this is clearly not happening here.

Most likely reason is that extra care is needed when using `executor.map(function, ...)` with a function that raises Exceptions. Refs:
* https://stackoverflow.com/questions/51071378/exception-handling-in-concurrent-futures-executor-map
* https://superfastpython.com/processpoolexecutor-exception-handling/#Exception_Handling_When_Calling_map
* https://stackoverflow.com/questions/74953271/is-it-safe-to-trow-exception-in-python-threadpool-executor-map

---

Most likely related: https://github.com/fractal-analytics-platform/fractal-server/issues/482.

@jluethi: in the current issue, can you confirm that the failing task was a parallel one?

**Comment by jluethi** [comment]
Hey Tommaso! Yes, it was a parallel task. Specifically, the Yokogawa to OME-Zarr one
