### ISSUE TITLE
Move `__VERSION__` to somewhere where we can find it even without settings

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#50]
It's useful to check the installed version even from an arbitrary environment, where required variables are not available.

However, we need to import `fractal_server.config`, which then fails as:
```
python -c 'import fractal_server.config; print(fractal_server.config.__VERSION__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tommaso/Fractal/fractal-server/fractal_server/config.py", line 58, in <module>
    class Settings(BaseSettings):
  File "/home/tommaso/Fractal/fractal-server/fractal_server/config.py", line 62, in Settings
    fail_getenv("DEPLOYMENT_TYPE")
  File "/home/tommaso/Fractal/fractal-server/fractal_server/config.py", line 30, in fail_getenv
    raise ValueError(f"Must provide environment variable {key}")
ValueError: Must provide environment variable DEPLOYMENT_TYPE
```

In `fractal-tasks-core`, I've placed `__VERSION__` in `fractal_tasks_core/__init__.py`.
@jacopo-exact, can I do the same here? (and then update the `bumpver` options in `pyproject.toml`)

The same question holds for the client repo, where we would need to import `fractal.client.config`.

**Comment by jacopo-exact** [comment]
go ahead. remember to update bumpver config accordingly.
