### ISSUE TITLE
If `Workflow.task_list` is empty, catch error on the server side

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#502]
When calling the apply endpoint for a workflow with an empty task_list, we should respond with an appropriate HTTP error (like 422) and message.
Right now we hit a `500 Internal Server Error`:
```python traceback
INFO:     127.0.0.1:46978 - "POST /api/v1/project/apply/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/tommaso/.local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/tommaso/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/tommaso/.local/lib/python3.8/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/tommaso/.local/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/tommaso/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/tommaso/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/tommaso/.local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/tommaso/.local/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/tommaso/.local/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/tommaso/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/tommaso/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/tommaso/.local/lib/python3.8/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/tommaso/.local/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/tommaso/.local/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/tommaso/.local/lib/python3.8/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/tommaso/.local/lib/python3.8/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/tommaso/miniconda3/envs/fractal-server-1.0.7/lib/python3.8/site-packages/fractal_server/app/api/v1/project.py", line 228, in apply_workflow
    validate_workflow_compatibility(
  File "/home/tommaso/miniconda3/envs/fractal-server-1.0.7/lib/python3.8/site-packages/fractal_server/app/runner/common.py", line 249, in validate_workflow_compatibility
    workflow.input_type != "Any"
  File "/home/tommaso/miniconda3/envs/fractal-server-1.0.7/lib/python3.8/site-packages/fractal_server/app/models/workflow.py", line 191, in input_type
    return self.task_list[0].task.input_type
IndexError: list index out of range
```

**Comment by tcompa** [comment]
* In `_get_dataset_check_owner`: also return the project
* In `get_dataset`, ignore the second return value of `_get_dataset_check_owner`
* Check other endpoints for use of `_get_dataset_check_owner`
* In apply endpoint: handle workflow with empty task list -> 422
* In apply endpoint: get input dataset and project via new `_get_dataset_check_owner`
* In apply endpoint: check whether other HTTPException are needed

 In `test_project_api.py`, add a new test `test_project_apply_failures` with several failure modes:
1. 422 for workflow with no tasks
2. 404 for missing dataset or workflow
