### ISSUE TITLE
[FMI deployment] task environment python executable simlink to server python leads to issues

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#556]
For automatic task collection: I run into an error where the python executable of the tasks can't be found: This leads to a task execution error that isn't caught well and shows up in the server terminal

```
Traceback (most recent call last):
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/fractal_server/app/runner/__init__.py", line 174, in submit_workflow
    output_dataset.meta = await process_workflow(
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/fractal_server/app/runner/_slurm/__init__.py", line 284, in process_workflow
    output_dataset_metadata = await async_wrap(_process_workflow)(
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/fractal_server/app/runner/common.py", line 306, in async_wrapper
    return await loop.run_in_executor(executor, pfunc)
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/fractal_server/app/runner/_slurm/__init__.py", line 249, in _process_workflow
    output_task_pars_fut = recursive_task_submission(
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/fractal_server/app/runner/_common.py", line 552, in recursive_task_submission
    task_pars_depend_future = recursive_task_submission(
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/fractal_server/app/runner/_common.py", line 552, in recursive_task_submission
    task_pars_depend_future = recursive_task_submission(
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/fractal_server/app/runner/_common.py", line 552, in recursive_task_submission
    task_pars_depend_future = recursive_task_submission(
  [Previous line repeated 2 more times]
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/fractal_server/app/runner/_common.py", line 596, in recursive_task_submission
    this_task_future.result()
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
fractal_server.app.runner.common.TaskExecutionError: ('Traceback (most recent call last):\n  File "BASEPATH_SERVER/fractal-server-1.1.0a1/lib/python3.9/site-packages/fractal_server/app/runner/_common.py", line 261, in call_single_task\n    _call_command_wrapper(\n  File "BASEPATH_SERVER/fractal-server-1.1.0a1/lib/python3.9/site-packages/fractal_server/app/runner/_common.py", line 171, in _call_command_wrapper\n    raise e\n  File "BASEPATH_SERVER/fractal-server-1.1.0a1/lib/python3.9/site-packages/fractal_server/app/runner/_common.py", line 165, in _call_command_wrapper\n    result = subprocess.run(  # nosec\n  File "BASEPATH_SERVER/fractal-server-1.1.0a1/lib/python3.9/subprocess.py", line 501, in run\n    with Popen(*popenargs, **kwargs) as process:\n  File "BASEPATH_SERVER/fractal-server-1.1.0a1/lib/python3.9/subprocess.py", line 947, in __init__\n    self._execute_child(args, executable, preexec_fn, close_fds,\n  File "BASEPATH_SERVER/fractal-server-1.1.0a1/lib/python3.9/subprocess.py", line 1819, in _execute_child\n    raise child_exception_type(errno_num, err_msg, err_filename)\nFileNotFoundError: [Errno 2] No such file or directory: \'TASKS/task-envs/.fractal/fractal-tasks-core0.8.1/venv/bin/python\'\n', 2, 'No such file or directory')
```

The core part appears to be this:
```
FileNotFoundError: [Errno 2] No such file or directory: \'/Path/TO/task-envs/.fractal/fractal-tasks-core0.8.1/venv/bin/python\'\n', 2, 'No such file or directory')
```

When checking in that venv/bin folder, it appears that the python executable is a sim-link (I think. When checking with ls-la, it's shown as python ->  Path/to/local/python/on/server/from/task/env/.conda/envs/fractal-server-1.1.0a1/bin/python) to the python executable of the fractal server python, but there's an issue with that python sim-link (it's underlined in black, text in red & blinking in my console).
1. Why would the Python executable be a simlink to the server Python?
2. Could that be changed, because the server Python is supposed to be a local Python executable on the server machine, which is not accessible from the cluster
3. Any idea why the sim-link may already be broken? When I try to manually activate the task environment from local machine that runs the server, it activates. But which python returns /usr/bin/python 

This happens reproducibly.

---

The reason this error is not caught well seems to be in how the exception string was supposed to be formed:

```
Traceback (most recent call last):
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/starlette/responses.py", line 170, in __call__
    await self.background()
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/starlette/background.py", line 43, in __call__
    await task()
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/starlette/background.py", line 26, in __call__
    await self.func(*self.args, **self.kwargs)
  File "BASEPATH.conda/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/fractal_server/app/runner/__init__.py", line 200, in submit_workflow
    exception_args_string = "\n".join(e.args)
TypeError: sequence item 1: expected str instance, int found
```

This can be triggered by errors related to not having the python executable as above

**Comment by jluethi** [comment]
One thing I still need to test: Running the server not from a local server python environment, but from one on the shared filesystem (which we wouldn't want to do long-term, but may be useful for debugging this and we anyway have one that's being used by Fractal-server)

**Comment by jluethi** [comment]
Ok, if I run the server from a Python environment on the share, I don't run into this issue.
The tasks still use an environment where the Python executables are simlinked to the ones from the server environment. But those simlinks no work, because they are both on the same share. In that case, the workflow actually runs :)

**Comment by tcompa** [comment]
Ref:
* https://github.com/fractal-analytics-platform/fractal-server/issues/538

**Comment by tcompa** [comment]
> This can be triggered by

Missing end of the comment?

**Comment by tcompa** [comment]
> Why would the Python executable be a simlink to the server Python?

This is `venv` behavior: it creates a whole independent environment, but only for the python interpreter that is currently used to call venv. That is, it does not create a new python interpreter (hence, for instance, you cannot select a different ptyhon version). This differs from conda, which also has its own python interpreter for each env (hence you can select any version).

To make it clear:
```
tommaso@exact:/tmp$ python3 -m venv venv

tommaso@exact:/tmp$ ls -la venv/bin/python3
lrwxrwxrwx 1 tommaso tommaso 16 Mar 14 11:17 venv/bin/python3 -> /usr/bin/python3
```

Now, I can see that this is possibly a problem in the FMI setup, where the fractal-server python is not visible to the users running tasks on the remote slurm nodes.

I don't have a solution ready, yet. Let's re-discuss it.

(great that you could try fractal over there, Joel, and raise relevant issue - thanks)

**Comment by jluethi** [comment]
> Missing end of the comment?

My bad. Should have been: "This can be triggered by errors related to not having the python executable as above" (fixed now)

> I don't have a solution ready, yet. Let's re-discuss it.

Let's briefly discuss tomorrow how we want to proceed on this question :) As said, we have a workaround to test things by running the server also from the share, but that shouldn't be a requirement long-term (I think).

**Comment by jluethi** [comment]
> Agreed. The best candidate solution at the moment would be to rely on [FRACTAL_SLURM_WORKER_PYTHON](https://fractal-analytics-platform.github.io/fractal-server/configuration/#fractal_server.config.Settings.FRACTAL_SLURM_WORKER_PYTHON), when it is set.
> 
> The scope of this variable is exactly to define an interpreter that can be seen from users running tasks on remote nodes. What if we also used it to create the task environments and pip-install the tasks? In principle those environments are also meant for the same use (i.e. they should be available for users on the remote slurm nodes). This change would probably go into the get_python_interpreter function, in tasks/collection.py.

Yes, that would make sense to me. In the case where we need to have a different python available on the cluster, the `FRACTAL_SLURM_WORKER_PYTHON` is intended to solve this :)
I'd be happy with exploring a solution like that. Long-term, we may want to think about additional flexibility to task collection (what if I need e.g. a specific Python version), but that doesn't need to be something we tackle here :)

**Comment by tcompa** [comment]
For the record, the fix of using FRACTAL_SLURM_WORKER_PYTHON for creating venvs and pip-installing tasks is not a complex one (see https://github.com/fractal-analytics-platform/fractal-server/pull/658/commits/e1526cc02ffa57be93390fc85c01421db3ff8921). What turns out to be a bit complex is testing in the docker-slurm CI - in progress.

**Comment by tcompa** [comment]
@jluethi is there still something to improve in the current FMI setup, after the new Python-interpreters configuration changes? If not, let's close this one.

**Comment by jluethi** [comment]
The whole issue of linking Pythons has been resolved with the explicit task base Pythons. As far as I can judge, this is all solved now :)
