### ISSUE TITLE
Catch error in workflow-apply endpoint

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#591]
If we are using a SLURM backend, and `user.slurm_user=None`, return an HTTPError.
Current failure:
```python traceback
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/data/homes/fractal/anaconda3/envs/fractal-server-new-slurm/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/homes/fractal/anaconda3/envs/fractal-server-new-slurm/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-new-slurm/lib/python3.9/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-new-slurm/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-new-slurm/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/data/homes/fractal/anaconda3/envs/fractal-server-new-slurm/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-new-slurm/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-new-slurm/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/data/homes/fractal/anaconda3/envs/fractal-server-new-slurm/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-new-slurm/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/data/homes/fractal/anaconda3/envs/fractal-server-new-slurm/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-new-slurm/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-new-slurm/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-new-slurm/lib/python3.9/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-new-slurm/lib/python3.9/site-packages/starlette/responses.py", line 174, in __call__
    await self.background()
  File "/data/homes/fractal/anaconda3/envs/fractal-server-new-slurm/lib/python3.9/site-packages/starlette/background.py", line 43, in __call__
    await task()
  File "/data/homes/fractal/anaconda3/envs/fractal-server-new-slurm/lib/python3.9/site-packages/starlette/background.py", line 26, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-new-slurm/lib/python3.9/site-packages/fractal_server/app/runner/__init__.py", line 149, in submit_workflow
    _mkdir_as_user(folder=str(WORKFLOW_DIR_USER), user=slurm_user)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-new-slurm/lib/python3.9/site-packages/fractal_server/app/runner/_slurm/_subprocess_run_as_user.py", line 86, in _mkdir_as_user
    raise RuntimeError(f"{user=} not allowed in _mkdir_as_user")
RuntimeError: user=None not allowed in _mkdir_as_user
```

**Comment by ychiucco** [comment]
Isn't this enough?
