### ISSUE TITLE
Project deletion currently not working when there is an associated workflow job

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#663]
When I press the delete button on a project, I get this in the console:
```
Acess to fetch at 'http://localhost:8011/api/v1/project/1' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

http://localhost:8011/api/v1/project/1 net::ERR_FAILED 500 (Internal Server Error)
window.fetch @ fetcher.js?v=53bac609:54
deleteProject @ project_api.js:87
handleDeleteProject @ ProjectsList.svelte:42
handleCallbackAction @ ConfirmActionButton.svelte:14
ProjectsList.svelte:47 TypeError: Failed to fetch
    at window.fetch (fetcher.js?v=53bac609:54:10)
    at deleteProject (project_api.js:87:26)
    at handleDeleteProject (ProjectsList.svelte:42:11)
    at HTMLButtonElement.handleCallbackAction (ConfirmActionButton.svelte:14:38)
(
```

I see nothing on the Svelte server or Fractal server though.
Regarding the CORS: All other calls (creating projects, new datasets, submitting workflows etc.) appears to be working, so not sure why this call fails.

I'm running fractal server 1.2.4, current main fractal web.
Deployment-wise, I'm using a postgres backend, gunicorn and an httpd proxy server in front of fractal-web
(on sqlite, project deletion leads to database issues on the fractal server side)

**Comment by jluethi** [comment]
Removing a project doesn't appear to work if there is an associated workflow job, gets this error on the server side:
```
Traceback (most recent call last):
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/fractal_server/app/api/v1/project.py", line 347, in delete_project
    await db.commit()
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/session.py", line 578, in commit
    return await greenlet_spawn(self.sync_session.commit)
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 136, in greenlet_spawn
    result = context.switch(value)
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1431, in commit
    self._transaction.commit(_to_root=self.future)
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3363, in flush
    self._flush(objects)
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3503, in _flush
    transaction.rollback(_capture_exception=True)
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3463, in _flush
    flush_context.execute()
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 667, in execute
    util.preloaded.orm_persistence.delete_obj(
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 343, in delete_obj
    _emit_delete_statements(
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1468, in _emit_delete_statements
    c = connection._execute_20(
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
    self.dialect.do_executemany(
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 729, in do_executemany
    cursor.executemany(statement, parameters)
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 484, in executemany
    return self._adapt_connection.await_(
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
    return current.driver.switch(awaitable)
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
    value = await result
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 476, in _executemany
    self._handle_exception(error)
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 389, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/data/homes/fractal/deployment_joel/fractal-demos/examples/server/fractal-server-1.2.4/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 682, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.IntegrityError: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.ForeignKeyViolationError'>: update or delete on table "dataset" violates foreign key constraint "applyworkflow_input_dataset_id_fkey" on table "applyworkflow"
DETAIL:  Key (id)=(1) is still referenced from table "applyworkflow".
```

**Comment by tcompa** [comment]
A job is in relationship with
* a project
* a workflow
* one or two datasets

Removing the project already removes the dataset(s), and in principle also the workflow (to be checked). The configuration for the job/project relationship is not correct.
