### ISSUE TITLE
SLURM-executor shutdown still "randomly" fails in the CI

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#690]
See https://github.com/fractal-analytics-platform/fractal-server/actions/runs/4959418983/jobs/8873493804

Failing test: tests/test_backend_slurm_shutdown.py::test_indirect_shutdown_during_submit.
```python traceback

    def test_indirect_shutdown_during_submit(
        monkey_slurm,
        monkey_slurm_user,
        tmp777_path,
        tmp_path,
        cfut_jobs_finished,
    ):
        """
        Test the FractalSlurmExecutor.shutdown method indirectly, that is, when it
        is triggered by the presence of a shutdown_file
        """
        shutdown_file = tmp_path / "shutdown"
    
        executor = FractalSlurmExecutor(
            slurm_user=monkey_slurm_user,
            working_dir=tmp777_path,
            working_dir_user=tmp777_path,
            slurm_poll_interval=2,
            keep_pickle_files=True,
            shutdown_file=str(shutdown_file),
        )
    
        res = executor.submit(_sleep_and_return, 100)
        debug(res)
        debug(run_squeue())
    
        with shutdown_file.open("w") as f:
            f.write("")
        assert shutdown_file.exists()
    
        time.sleep(5)
    
        debug(res)
        debug(run_squeue())
    
        assert not run_squeue(header=False)
        with pytest.raises(JobExecutionError):
>           _ = res.result()

tests/test_backend_slurm_shutdown.py:86: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/concurrent/futures/_base.py:439: in result
    return self.__get_result()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = None

    def __get_result(self):
        if self._exception:
            try:
>               raise self._exception
E               fractal_server.app.runner.common.TaskExecutionError: ModuleNotFoundError: No module named 'tests'

/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/concurrent/futures/_base.py:391: TaskExecutionError
```

```python traceback

tests/test_backend_slurm.py::test_slurm_executor_map_with_exception[late]
  /home/runner/.cache/pypoetry/virtualenvs/fractal-server-21eqDTaF-py3.9/lib/python3.9/site-packages/_pytest/threadexception.py:73: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-5
  
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/threading.py", line 980, in _bootstrap_inner
      self.run()
    File "/home/runner/work/fractal-server/fractal-server/fractal_server/app/runner/_slurm/_executor_wait_thread.py", line 103, in run
      self.check(i)
    File "/home/runner/work/fractal-server/fractal-server/fractal_server/app/runner/_slurm/_executor_wait_thread.py", line 137, in check
      self.callback(finished_id)
    File "/home/runner/work/fractal-server/fractal-server/fractal_server/app/runner/_slurm/executor.py", line 681, in _completion
      fut, job = self.jobs.pop(jobid)
  KeyError: '15'
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))
```

**Comment by tcompa** [comment]
The main error (i.e. the importerror) was related to the way we wrote the test, where a certain function defined in the test module was pickled by-reference. Note that this error cannot take place when actually running fractal-server (and not the CI), because we have the fractal-server package installed on both server and worker side.

We fix the test by using https://github.com/cloudpipe/cloudpickle#overriding-pickles-serialization-mechanism-for-importable-constructs.

Some details (now written as a comment in the test module):
```
'''
NOTE: the experimental `register_pickle_by_value` feature of cloudpickle>=2
is described in
https://github.com/cloudpipe/cloudpickle#overriding-pickles-serialization-mechanism-for-importable-constructs.
Briefly:
1. It allows us to unpickle a function even if we don't have access to the
   module where it was defined.
2. It is experimental and can fail for some relevant cases (e.g. functions
   that include other imports, or a mix of by-value/by-reference pickling).
For us, this feature could be quite useful as part of the CI, to avoid
unexpected errors as in
https://github.com/fractal-analytics-platform/fractal-server/issues/690.
'''
```

**Comment by tcompa** [comment]
EDIT: the solution described above (and implemented in https://github.com/fractal-analytics-platform/fractal-server/commit/6f272197b2d325a26f80aa6bd3777142bff16243) supposedly should work, but has some unexpected behavior and it's not worth spending too much time investigating (since it only relates to the CI).

We are now switching back to the simplest solution (see a8f5e5a6), that is, defining auxiliary functions from within test functions.
