### ISSUE TITLE
sqlite `_engine_async` and `greenlet` dependency

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#747]
I started testing the newest Fractal server pre-releases locally and ran into these 2 errors when starting the server:

```
 File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/fractal_server/app/db/__init__.py", line 32, in engine_async
    return cls._engine_async
AttributeError: type object 'DB' has no attribute '_engine_async'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/bin/fractalctl", line 8, in <module>
    sys.exit(run())
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/fractal_server/__main__.py", line 83, in run
    set_db()
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/fractal_server/__main__.py", line 74, in set_db
    alembic.config.main(argv=alembic_args)
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/alembic/config.py", line 632, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/alembic/config.py", line 626, in main
    self.run_cmd(cfg, options)
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/alembic/config.py", line 603, in run_cmd
    fn(
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/alembic/command.py", line 385, in upgrade
    script.run_env()
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/alembic/script/base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/fractal_server/migrations/env.py", line 84, in <module>
    asyncio.run(run_migrations_online())
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/fractal_server/migrations/env.py", line 74, in run_migrations_online
    engine = DB.engine_async()
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/fractal_server/app/db/__init__.py", line 34, in engine_async
    cls.set_db()
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/fractal_server/app/db/__init__.py", line 67, in set_db
    cls._engine_async = create_async_engine(
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/engine.py", line 43, in create_async_engine
    sync_engine = _create_engine(*arg, **kw)
  File "<string>", line 2, in create_engine
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 660, in create_engine
    event.listen(pool, "connect", on_connect)
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/sqlalchemy/event/api.py", line 115, in listen
    _event_key(target, identifier, fn).listen(*args, **kw)
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/sqlalchemy/event/registry.py", line 232, in listen
    self.dispatch_target.dispatch._listen(self, *args, **kw)
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/sqlalchemy/pool/events.py", line 69, in _listen
    event_key.base_listen(**kw)
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/sqlalchemy/event/registry.py", line 270, in base_listen
    for_modify._set_asyncio()
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 265, in _set_asyncio
    self._exec_once_mutex = AsyncAdaptedLock()
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/sqlalchemy/util/concurrency.py", line 67, in AsyncAdaptedLock
    _not_implemented()
  File "/Users/joel/mambaforge/envs/fractal-server-1.3.0a5/lib/python3.9/site-packages/sqlalchemy/util/concurrency.py", line 47, in _not_implemented
    raise ValueError(
ValueError: the greenlet library is required to use this function. No module named 'greenlet'

```

**Comment by jluethi** [comment]
Manually installing greenlet as `pip install greenlet` then makes both errors disappear & the server start up correctly

**Comment by tcompa** [comment]
Can you report more details about the installation procedure?

In principle fractal-server requires sqlalchemy, which requires greenlet, so that this should not happen.

After installing fractal-server, is sqlalchemy installed?

**Comment by jluethi** [comment]
I installed fractal-server without any of the extras this way:

```
VERSION="1.3.0a5"

ENVNAME=fractal-server-$VERSION
conda deactivate
conda remove --name $ENVNAME -y --all
conda create --name $ENVNAME python==3.9 -y
conda activate $ENVNAME
conda update pip -y

pip install "fractal-server"==$VERSION
```

And then tried to launch fractal-server using the `server_config_and_start.sh` script (and setting `FRACTAL_RUNNER_BACKEND=local`, rest on settings as here: https://github.com/fractal-analytics-platform/fractal-demos/blob/114c4fd449bdd069a5f04e7dc9ab772acaf56db8/examples/server/server_config_and_start.sh

I did a pip list after the installation now:
```
Package           Version
----------------- --------
aiosqlite         0.17.0
alembic           1.11.1
anyio             3.7.0
bcrypt            4.0.1
certifi           2023.5.7
cffi              1.15.1
click             8.1.3
cryptography      41.0.1
dnspython         2.3.0
email-validator   1.3.1
exceptiongroup    1.1.1
fastapi           0.95.2
fastapi-users     10.4.2
fractal-server    1.3.0a5
h11               0.14.0
httpcore          0.16.3
httpx             0.23.3
httpx-oauth       0.11.2
idna              3.4
makefun           1.15.1
Mako              1.2.4
MarkupSafe        2.1.3
passlib           1.7.4
pip               23.1.2
pycparser         2.21
pydantic          1.10.9
PyJWT             2.6.0
python-dotenv     0.20.0
python-multipart  0.0.6
rfc3986           1.5.0
setuptools        67.7.2
sniffio           1.3.0
SQLAlchemy        1.4.41
SQLAlchemy-Utils  0.38.3
sqlalchemy2-stubs 0.0.2a34
sqlmodel          0.0.8
starlette         0.27.0
typing_extensions 4.6.3
uvicorn           0.20.0
wheel             0.40.0
```

sqalchemy is there, but greenlet is not. Maybe an issue with a dependency being in the extras that should be in core?

I tried installing it again with the extras (which shouldn't be necessary for this local setup), as in `[slurm,gunicorn,postgres]`. Unfortunately, `psycopg2` installation seems a bit trickier on my Mac, need a `pg_config` to build it from source, which appears to be missing. I thus can't fully verify this hypothesis

**Comment by jluethi** [comment]
Hmm, really weird indeed. I thought maybe it's Python 3.9 vs. 3.10, but that doesn't appear to be the case. In neither case does greenlet show up as a SQLAlchemy dependency for me on macos.

---

With Python 3.9, I get:
```
pip show sqlalchemy
Name: SQLAlchemy
Version: 1.4.41
Summary: Database Abstraction Library
Home-page: https://www.sqlalchemy.org
Author: Mike Bayer
Author-email: mike_mp@zzzcomputing.com
License: MIT
Location: /Users/joel/mambaforge/envs/fractal-server-test-1.3.0a5/lib/python3.9/site-packages
Requires: 
Required-by: alembic, fractal-server, SQLAlchemy-Utils, sqlmodel

pip --version
pip 23.1.2 from /Users/joel/mambaforge/envs/fractal-server-test-1.3.0a5/lib/python3.9/site-packages/pip (python 3.9)
```
=> greenlet doesn't show up here

-------

Trying the same with Python 3.10:

```
pip show sqlalchemy
Name: SQLAlchemy
Version: 1.4.41
Summary: Database Abstraction Library
Home-page: https://www.sqlalchemy.org
Author: Mike Bayer
Author-email: mike_mp@zzzcomputing.com
License: MIT
Location: /Users/joel/mambaforge/envs/fractal-server-test-1.3.0a5/lib/python3.10/site-packages
Requires: 
Required-by: alembic, fractal-server, SQLAlchemy-Utils, sqlmodel

pip --version
pip 23.1.2 from /Users/joel/mambaforge/envs/fractal-server-test-1.3.0a5/lib/python3.10/site-packages/pip (python 3.10)
```

**Comment by jluethi** [comment]
Ah, apparently it's related to this here: https://docs.sqlalchemy.org/en/20/faq/installation.html

**Comment by tcompa** [comment]
Ok, good to know.

Then let's add the greenlet dependency explicitly to fractal-server, to avoid this issue.

**Comment by jluethi** [comment]
Seems like a good way to go. The pip installation of greenlet worked without issues on my side :)
