### ISSUE TITLE
Clarify whether non-absolute `FRACTAL_TASKS_DIR` is supported

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#823]
If we only support absolute paths, this should be both written in the documentation and hard-checked upon loading env variables.

Right now, I find a bug where setting `FRACTAL_TASKS_DIR=Tasks` (i.e. a non-absolute path) leads to error in the identification of the venv/package paths:
```python traceback
2023-09-07 09:53:26,164 - fractal-tasks-core - INFO - Background collection failed. Original error: [Errno 2] No such file or directory: 'Tasks/.fractal/fractal-tasks-core0.11.0a1/venv/bin/pip'
CRITICAL:root:venv_path=PosixPath('Tasks/.fractal/fractal-tasks-core0.11.0a1')
ERROR:root:B/FROM Tasks/Tasks/.fractal/fractal-tasks-core0.11.0a1 to Tasks/.fractal/fractal-tasks-core0.11.0a1
CRITICAL:root:package_path=PosixPath('Tasks/Tasks/.fractal/fractal-tasks-core0.11.0a1')
CRITICAL:root:log_path=PosixPath('Tasks/Tasks/.fractal/fractal-tasks-core0.11.0a1/collection.log')
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/tommaso/Fractal/fractal-server/fractal_server/app/api/v1/task_collection.py", line 82, in _background_collect_pip
    task_list = await create_package_environment_pip(
  File "/home/tommaso/Fractal/fractal-server/fractal_server/tasks/collection.py", line 398, in create_package_environment_pip
    raise e
  File "/home/tommaso/Fractal/fractal-server/fractal_server/tasks/collection.py", line 359, in create_package_environment_pip
    python_bin, package_root = await _create_venv_install_package(
  File "/home/tommaso/Fractal/fractal-server/fractal_server/tasks/collection.py", line 424, in _create_venv_install_package
    package_root = await _pip_install(
  File "/home/tommaso/Fractal/fractal-server/fractal_server/tasks/collection.py", line 488, in _pip_install
    await execute_command(
  File "/home/tommaso/Fractal/fractal-server/fractal_server/utils.py", line 63, in execute_command
    proc = await asyncio.create_subprocess_exec(
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1681, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 207, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 799, in _start
    self._proc = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'Tasks/.fractal/fractal-tasks-core0.11.0a1/venv/bin/pip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/responses.py", line 174, in __call__
    await self.background()
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/background.py", line 43, in __call__
    await task()
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/background.py", line 26, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/home/tommaso/Fractal/fractal-server/fractal_server/app/api/v1/task_collection.py", line 126, in _background_collect_pip
    data.log = get_collection_log(venv_path)
  File "/home/tommaso/Fractal/fractal-server/fractal_server/tasks/collection.py", line 103, in get_collection_log
    log = log_path.open().read()
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: 'Tasks/Tasks/.fractal/fractal-tasks-core0.11.0a1/collection.log'
```

**Comment by tcompa** [comment]
Closed with #803
