### ISSUE TITLE
Submitting as 2 different users to the same server leads to 500 Internal Server Error

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#84]
I've been trying to submit similar jobs to the cluster using 2 different users. This leads to an internal server error when the second user submits jobs:

```
INFO:     127.0.0.1:39012 - "POST /api/v1/project/apply/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/fractal_server/app/api/v1/project.py", line 148, in apply_workflow
    project, input_dataset = (await db.execute(stm)).one()
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1191, in one
    return self._only_one_row(
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 562, in _only_one_row
    raise exc.NoResultFound(
sqlalchemy.exc.NoResultFound: No row was found when one was required
```

It's using different project names, dataset names, workflow names and output paths. I don't see any other error messages on the server side. The client side just reports this, without an error message.

```
DEBUG:root:500
ERROR:root:Server returned 500
ERROR:root:Original request: POST http://localhost:8000/api/v1/project/2/2
ERROR:root:Original payload: {"path": "../images/10.5281_zenodo.7057076", "glob_pattern": "*.png"}
ERROR:root:Server error message: {}

ERROR:root:Terminating.

```

Individually, both examples run. If I run one after the other without restarting the server, I get this error.

**Comment by jluethi** [comment]
Full setup with example files, user .fractal.env files etc can be found here:
`/data/homes/jluethi/fractal_3repo/fractal/examples/08_1_Run2`
`/data/homes/jluethi/fractal_3repo/fractal/examples/08_2_Run2`

**Comment by jluethi** [comment]
Hmm, I'm actually hitting a similar error when trying to submit 2 workflows from the same user. So it's not related to multi-user necessarily. 

The second project does get registered for user number 2. But when preparing the input dataset, I hit this error. 

```
DEBUG:root:200                                                                                                                                                                                     
{                                                                                                                                                                                                  
  "name": "Run_2_input-ds",                                                                                                                                                                        
  "project_id": 1,                                                                                                                                                                                 
  "type": "image",                                                                                                                                                                                 
  "meta": {},                                                                                                                                                                                      
  "read_only": true,                                                                                                                                                                               
  "id": 2,                                                                                                                                                                                         
  "resource_list": [                                                                                                                                                                               
    {                                                                                                                                                                                              
      "path": "/data/active/jluethi/Fractal/Run_1_20220927_2x2_Zenodo",                                                                                                                            
      "glob_pattern": "*.zarr",                                                                                                                                                                    
      "id": 2,                                                                                                                                                                                     
      "dataset_id": 2                                                                                                                                                                              
    }                                                                                                                                                                                              
  ]                                                                                                                                                                                                
}                                                                                                                                                                                                  
DEBUG:asyncio:Using selector: EpollSelector                                                                                                                                                        
DEBUG:root:Namespace(batch=False, cmd='dataset', dataset_id=2, glob_pattern='*.png', json=False, password=None, path='../images/10.5281_zenodo.7057076', project_id=2, subcmd='add-resource', user=
None, v=0)                                                                                                                                                                                         
DEBUG:root:AuthClient test2@me.com test                                                                                                                                                            
DEBUG:httpx._client:HTTP Request: POST http://localhost:8000/auth/token/login "HTTP/1.1 200 OK"                                                                                                    
DEBUG:httpx._client:HTTP Request: POST http://localhost:8000/api/v1/project/2/2 "HTTP/1.1 500 Internal Server Error"                                                                               
DEBUG:root:500                                                                                                                                                                                     
ERROR:root:Server returned 500                                                                                                                                                                     
ERROR:root:Original request: POST http://localhost:8000/api/v1/project/2/2                                                                                                                         
ERROR:root:Original payload: {"path": "../images/10.5281_zenodo.7057076", "glob_pattern": "*.png"}                                                                                                 
ERROR:root:Server error message: {}                                                                                                                                                                
                                                                                                                                                                                                   ERROR:root:Terminating.   
```

**Comment by tcompa** [comment]
I'm wondering if this is really a server error, or if something goes wrong in the example scripts (e.g. getting the wrong ID for some object). I'll test it further.

**Comment by tcompa** [comment]
Still, the server should return a more informative error.

**Comment by jluethi** [comment]
@tcompa Any idea why we would be getting wrong IDs here? This is currently my top priority, as it's the only remaining blocking issue for Wednesday's demo.
If we should to debug something together, let me know.

**Comment by tcompa** [comment]
Yes, the script is just wrong. A working version `script.py` reads:
```python
import json
import sys


assert len(sys.argv[1:]) > 1

filename, which_id = sys.argv[1:3]
if which_id == "dataset_id":
    assert len(sys.argv[1:]) == 3
    dataset_name = sys.argv[3]

with open(filename, "r") as fin:
    d = json.load(fin)

if which_id == "project_id":
    # Safety check
    assert "project_dir" in d.keys()
    print(d["id"])
elif which_id == "dataset_id":
    dataset_list = d["dataset_list"]
    dataset_id = next(ds["id"]
                      for ds in dataset_list
                      if ds["name"] == dataset_name)
    print(dataset_id)
else:
    raise Exception("ERROR: {which_id=}")
```
and it can be called as
```
python script.py file.json project_id
```
or
```
python script.py file.json dataset_id default
```

I'm updating this in the examples (where I'd like to include more by-name task choice as well).

**Comment by jluethi** [comment]
Ah, that's good to hear! Which part of the script was at fault? And what is the script.py? Let me know when you have an example, I'd like to test this on the FMI setup as soon as possible.

I'm trying to update this example here to run for the demo: https://github.com/jluethi/fractal-demos/blob/main/demo-october-2022/example_2x2_cardio_fmi/run_fractal_demo.sh
