### ISSUE TITLE
Better display of Unknown Error

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#843]
Ref https://github.com/fractal-analytics-platform/fractal-server/issues/842

The one in that issue is likely a `KeyError`, which should be part of the error message.

**Comment by tcompa** [comment]
```python
import traceback


class MyError(RuntimeError):
    pass


try:
    meta = {}
    meta["image"]
except Exception as e:
    print(traceback.format_exc())


try:
    raise MyError("Error message")
    meta["image"]
except Exception as e:
    print(traceback.format_exc())
```
writes
```
Traceback (most recent call last):
  File "/tmp/x.py", line 10, in <module>
    meta["image"]
KeyError: 'image'

Traceback (most recent call last):
  File "/tmp/x.py", line 16, in <module>
    raise MyError("Error message")
MyError: Error message
```

**Comment by tcompa** [comment]
Ref 487fbb693cf67947a727ae2faa0630f76b8d6a95
