### ISSUE TITLE
500 internal error on task collection

### ISSUE THREAD

**Issue by mfranzon** [fractal-analytics-platform/fractal-server#866]
```
ERROR:root:Server returned 500
ERROR:root:Original request: POST http://fractal-server:8000/api/v1/task/collect/pip/
ERROR:root:Original payload: {"package": "fractal-tasks-core", "package_version": "0.11.0", "package_extras": "fractal-tasks"}
ERROR:root:Server error message: {}

ERROR:root:Terminating.
```

**Comment by tcompa** [comment]
To test:
* collect tasks
* remove venv folders
* collect tasks again

**Comment by tcompa** [comment]
```python
2023-09-28 10:41:33,278 - fractal-tasks-core - INFO - Background collection failed. Original error: (sqlite3.IntegrityError) UNIQUE constraint failed: task.source
[SQL: INSERT INTO task (meta, args_schema, source, name, command, input_type, output_type, owner, version, args_schema_version, docs_info, docs_link) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('{"cpus_per_task": 1, "mem": 4000}', '{"title": "CreateOmeZarr", "type": "object", "properties": {"input_paths": {"title": "Input Paths", "type": "array", "items": {"type": "string"}, "de ... (4423 characters truncated) ... title": "Inverted", "default": false, "type": "boolean", "description": "Do not change. Omero-channel attribute."}}, "required": ["wavelength_id"]}}}', 'pip_remote:fractal_tasks_core:0.12.0:fractal-tasks::create_ome-zarr_structure', 'Create OME-Zarr structure', '/home/tommaso/Fractal/fractal-server/tests/data/example_server_startup/Tasks/.fractal/fractal-tasks-core0.12.0/venv/bin/python /home/tommaso/Fractal/ ... (17 characters truncated) ... sts/data/example_server_startup/Tasks/.fractal/fractal-tasks-core0.12.0/venv/lib/python3.10/site-packages/fractal_tasks_core/tasks/create_ome_zarr.py', 'image', 'zarr', None, '0.12.0', 'pydantic_v1', 'Create a OME-NGFF zarr folder, without reading/writing image data.\n\nFind plates (for each folder in input_paths):\n\n- glob image files,\n- parse m ... (119 characters truncated) ... ):\n\n- parse mlf metadata,\n- identify wells and field of view (FOV),\n- create FOV ZARR,\n- verify that channels are uniform (i.e., same channels).', HttpUrl('https://fractal-analytics-platform.github.io/fractal-tasks-core/reference/fractal_tasks_core/tasks/create_ome_zarr/#fractal_tasks_core.tasks.create_ome_zarr.create_ome_zarr', ))]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: task.source

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tommaso/Fractal/fractal-server/fractal_server/app/api/v1/task_collection.py", line 94, in _background_collect_pip
    tasks = await _insert_tasks(task_list=task_list, db=db)
  File "/home/tommaso/Fractal/fractal-server/fractal_server/app/api/v1/task_collection.py", line 145, in _insert_tasks
    db.commit()
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3386, in flush
    self._flush(objects)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3525, in _flush
    with util.safe_reraise():
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3486, in _flush
    flush_context.execute()
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: task.source
[SQL: INSERT INTO task (meta, args_schema, source, name, command, input_type, output_type, owner, version, args_schema_version, docs_info, docs_link) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('{"cpus_per_task": 1, "mem": 4000}', '{"title": "CreateOmeZarr", "type": "object", "properties": {"input_paths": {"title": "Input Paths", "type": "array", "items": {"type": "string"}, "de ... (4423 characters truncated) ... title": "Inverted", "default": false, "type": "boolean", "description": "Do not change. Omero-channel attribute."}}, "required": ["wavelength_id"]}}}', 'pip_remote:fractal_tasks_core:0.12.0:fractal-tasks::create_ome-zarr_structure', 'Create OME-Zarr structure', '/home/tommaso/Fractal/fractal-server/tests/data/example_server_startup/Tasks/.fractal/fractal-tasks-core0.12.0/venv/bin/python /home/tommaso/Fractal/ ... (17 characters truncated) ... sts/data/example_server_startup/Tasks/.fractal/fractal-tasks-core0.12.0/venv/lib/python3.10/site-packages/fractal_tasks_core/tasks/create_ome_zarr.py', 'image', 'zarr', None, '0.12.0', 'pydantic_v1', 'Create a OME-NGFF zarr folder, without reading/writing image data.\n\nFind plates (for each folder in input_paths):\n\n- glob image files,\n- parse m ... (119 characters truncated) ... ):\n\n- parse mlf metadata,\n- identify wells and field of view (FOV),\n- create FOV ZARR,\n- verify that channels are uniform (i.e., same channels).', HttpUrl('https://fractal-analytics-platform.github.io/fractal-tasks-core/reference/fractal_tasks_core/tasks/create_ome_zarr/#fractal_tasks_core.tasks.create_ome_zarr.create_ome_zarr', ))]
(Background on this error at: https://sqlalche.me/e/14/gkpj)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/responses.py", line 174, in __call__
    await self.background()
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/background.py", line 43, in __call__
    await task()
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/starlette/background.py", line 26, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/home/tommaso/Fractal/fractal-server/fractal_server/app/api/v1/task_collection.py", line 129, in _background_collect_pip
    db.commit()
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 827, in commit
    self._assert_active(prepared_ok=True)
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 601, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: task.source
[SQL: INSERT INTO task (meta, args_schema, source, name, command, input_type, output_type, owner, version, args_schema_version, docs_info, docs_link) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('{"cpus_per_task": 1, "mem": 4000}', '{"title": "CreateOmeZarr", "type": "object", "properties": {"input_paths": {"title": "Input Paths", "type": "array", "items": {"type": "string"}, "de ... (4423 characters truncated) ... title": "Inverted", "default": false, "type": "boolean", "description": "Do not change. Omero-channel attribute."}}, "required": ["wavelength_id"]}}}', 'pip_remote:fractal_tasks_core:0.12.0:fractal-tasks::create_ome-zarr_structure', 'Create OME-Zarr structure', '/home/tommaso/Fractal/fractal-server/tests/data/example_server_startup/Tasks/.fractal/fractal-tasks-core0.12.0/venv/bin/python /home/tommaso/Fractal/ ... (17 characters truncated) ... sts/data/example_server_startup/Tasks/.fractal/fractal-tasks-core0.12.0/venv/lib/python3.10/site-packages/fractal_tasks_core/tasks/create_ome_zarr.py', 'image', 'zarr', None, '0.12.0', 'pydantic_v1', 'Create a OME-NGFF zarr folder, without reading/writing image data.\n\nFind plates (for each folder in input_paths):\n\n- glob image files,\n- parse m ... (119 characters truncated) ... ):\n\n- parse mlf metadata,\n- identify wells and field of view (FOV),\n- create FOV ZARR,\n- verify that channels are uniform (i.e., same channels).', HttpUrl('https://fractal-analytics-platform.github.io/fractal-tasks-core/reference/fractal_tasks_core/tasks/create_ome_zarr/#fractal_tasks_core.tasks.create_ome_zarr.create_ome_zarr', ))]
```
