### ISSUE TITLE
`pip install` from clean conda env leads to `ModuleNotFoundError: No module named 'six'`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#868]
Note that the same works fine from within a standard venv.

Error traceback:
```
Channels:
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.

Collecting fractal-server[gunicorn,postgres,slurm]==1.3.8a0
  Obtaining dependency information for fractal-server[gunicorn,postgres,slurm]==1.3.8a0 from https://files.pythonhosted.org/packages/60/53/ad6f731e5cc0557522945a77e123600ac9c405e02951910ff190c8e2855a/fractal_server-1.3.8a0-py3-none-any.whl.metadata
  Using cached fractal_server-1.3.8a0-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: SQLAlchemy-Utils<0.39.0,>=0.38.3 in /home/tommaso/.local/lib/python3.10/site-packages (from fractal-server[gunicorn,postgres,slurm]==1.3.8a0) (0.38.3)
Requirement already satisfied: aiosqlite<0.18.0,>=0.17.0 in /home/tommaso/.local/lib/python3.10/site-packages (from fractal-server[gunicorn,postgres,slurm]==1.3.8a0) (0.17.0)
Requirement already satisfied: alembic<2.0.0,>=1.9.1 in /home/tommaso/.local/lib/python3.10/site-packages (from fractal-server[gunicorn,postgres,slurm]==1.3.8a0) (1.11.1)
Requirement already satisfied: fastapi<0.96.0,>=0.95.0 in /home/tommaso/.local/lib/python3.10/site-packages (from fractal-server[gunicorn,postgres,slurm]==1.3.8a0) (0.95.2)
Requirement already satisfied: fastapi-users[oauth]<11.0,>=10.1 in /home/tommaso/.local/lib/python3.10/site-packages (from fractal-server[gunicorn,postgres,slurm]==1.3.8a0) (10.4.2)
Requirement already satisfied: greenlet in /home/tommaso/.local/lib/python3.10/site-packages (from fractal-server[gunicorn,postgres,slurm]==1.3.8a0) (2.0.2)
Requirement already satisfied: pydantic<2,>=1.10.8 in /home/tommaso/.local/lib/python3.10/site-packages (from fractal-server[gunicorn,postgres,slurm]==1.3.8a0) (1.10.12)
Requirement already satisfied: python-dotenv<0.21.0,>=0.20.0 in /home/tommaso/.local/lib/python3.10/site-packages (from fractal-server[gunicorn,postgres,slurm]==1.3.8a0) (0.20.0)
Requirement already satisfied: sqlalchemy<2.0,>=1.4 in /home/tommaso/.local/lib/python3.10/site-packages (from fractal-server[gunicorn,postgres,slurm]==1.3.8a0) (1.4.41)
Requirement already satisfied: sqlmodel<0.0.9,>=0.0.8 in /home/tommaso/.local/lib/python3.10/site-packages (from fractal-server[gunicorn,postgres,slurm]==1.3.8a0) (0.0.8)
Requirement already satisfied: uvicorn<0.21.0,>=0.20.0 in /home/tommaso/.local/lib/python3.10/site-packages (from fractal-server[gunicorn,postgres,slurm]==1.3.8a0) (0.20.0)
Collecting asyncpg<0.28.0,>=0.27.0 (from fractal-server[gunicorn,postgres,slurm]==1.3.8a0)
  Using cached asyncpg-0.27.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl (2.6 MB)
Collecting psycopg2<3.0.0,>=2.9.5 (from fractal-server[gunicorn,postgres,slurm]==1.3.8a0)
  Using cached psycopg2-2.9.7.tar.gz (383 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-dhzm0qew/psycopg2_25fbcff979c9456cbb03a1fffe8c7097/setup.py", line 551, in <module>
          setup(name="psycopg2",
        File "/home/tommaso/miniconda3/envs/fractal-server-1.3.8a0/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/home/tommaso/miniconda3/envs/fractal-server-1.3.8a0/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/home/tommaso/miniconda3/envs/fractal-server-1.3.8a0/lib/python3.10/site-packages/setuptools/dist.py", line 486, in __init__
          _Distribution.__init__(
        File "/home/tommaso/miniconda3/envs/fractal-server-1.3.8a0/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/home/tommaso/miniconda3/envs/fractal-server-1.3.8a0/lib/python3.10/site-packages/setuptools/dist.py", line 924, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/home/tommaso/miniconda3/envs/fractal-server-1.3.8a0/lib/python3.10/site-packages/setuptools/dist.py", line 923, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/home/tommaso/miniconda3/envs/fractal-server-1.3.8a0/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
          module = import_module(match.group('module'))
        File "/home/tommaso/miniconda3/envs/fractal-server-1.3.8a0/lib/python3.10/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 883, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "/home/tommaso/.local/lib/python3.10/site-packages/npe2/__init__.py", line 4, in <module>
          __version__ = version("npe2")
        File "/home/tommaso/miniconda3/envs/fractal-server-1.3.8a0/lib/python3.10/importlib/metadata/__init__.py", line 947, in version
          debug(distribution(distribution_name))
        File "/home/tommaso/.local/lib/python3.10/site-packages/devtools/debug.py", line 116, in __call__
          d_out = self._process(args, kwargs)
        File "/home/tommaso/.local/lib/python3.10/site-packages/devtools/debug.py", line 184, in _process
          arguments = list(self._process_args(ex, args, kwargs))
        File "/home/tommaso/.local/lib/python3.10/site-packages/devtools/debug.py", line 204, in _process_args
          atok = ex.source.asttokens()
        File "/home/tommaso/.local/lib/python3.10/site-packages/executing/executing.py", line 439, in asttokens
          import asttokens  # must be installed separately
        File "/home/tommaso/.local/lib/python3.10/site-packages/asttokens/__init__.py", line 22, in <module>
          from .asttokens import ASTText, ASTTokens, supports_tokenless
        File "/home/tommaso/.local/lib/python3.10/site-packages/asttokens/asttokens.py", line 23, in <module>
          import six
      ModuleNotFoundError: No module named 'six'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by tcompa** [comment]
I was a weird issue with my system environment, fixed by pip-uninstalling a bunch of packages (from outside the conda env).
Closing.
