### ISSUE TITLE
Unknown error in server 1.3.8

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#878]
I had to update the Fractal server at UZH today (unrelated, was a Python 3.9.0 issue, see https://github.com/fractal-analytics-platform/fractal-demos/issues/65). I thought I'd also update to fractal-server-1.3.8, as that looked to perform well in all the testing and wasn't a major change.
Unfortunately, it brok on production when trying to run a workflow with the following error.

I now went back to running a 1.3.6 server (with Python 3.10), so production is running again. But we should figure out what caused this issue.

```
UNKNOWN ERROR
Original error: Traceback (most recent call last):
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.3.8/lib/python3.10/site-packages/fractal_server/app/runner/__init__.py", line 228, in submit_workflow
    output_dataset_meta = await process_workflow(
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.3.8/lib/python3.10/site-packages/fractal_server/app/runner/_slurm/__init__.py", line 125, in process_workflow
    output_dataset_metadata = await async_wrap(_process_workflow)(
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.3.8/lib/python3.10/site-packages/fractal_server/app/runner/common.py", line 244, in async_wrapper
    return await loop.run_in_executor(executor, pfunc)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.3.8/lib/python3.10/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.3.8/lib/python3.10/site-packages/fractal_server/app/runner/_slurm/__init__.py", line 77, in _process_workflow
    output_task_pars = execute_tasks(
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.3.8/lib/python3.10/site-packages/fractal_server/app/runner/_common.py", line 617, in execute_tasks
    current_task_pars = call_parallel_task(
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.3.8/lib/python3.10/site-packages/fractal_server/app/runner/_common.py", line 510, in call_parallel_task
    for key, val in this_meta_update.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by tcompa** [comment]
Most likely cause is that this was a scmultiplex task, which does not write a valid dictionary to the output JSON file, but just a `null` value (since there is no `return {}` [here](https://github.com/fmi-basel/gliberal-scMultipleX/blob/main/src/scmultiplex/fractal/scmultiplex_feature_measurements.py#L410)).

Our tests always return a dictionary, and that's why this was not caught.

I'll release 1.3.9 shortly, also covering the `null` case.

**Comment by jluethi** [comment]
Ah that would make sense :)

**Comment by tcompa** [comment]
> I'll release 1.3.9 shortly, also covering the null case.

The new use case should be now covered in 1.3.9.
